import { ActionDefinition } from '../action-definition';
import { BelongingActionTag } from '../action-tags';
import { NeedTag } from '../needs';

export const BelongingActions: ActionDefinition[] = [
    {
        tag: BelongingActionTag.JOIN_CLAN,
        need: NeedTag.BELONGING,
        costEnergy: -0.2,
        costTime: 2,
        rewardSatisfaction: 0.9,
        rewardSecondary: { STABILITY: 0.4, LOYALTY: 0.4, TRUST: 0.3 },
        socialImpact: { ACCEPTANCE: 0.6 },
    },
    {
        tag: BelongingActionTag.ATTEND_GATHERING,
        need: NeedTag.BELONGING,
        costEnergy: -0.1,
        costTime: 1.5,
        rewardSatisfaction: 0.6,
        rewardSecondary: { COMMUNITY: 0.5, TRADITION: 0.3 },
        socialImpact: { VISIBILITY: 0.2, COHESION: 0.3 },
    },
    {
        tag: BelongingActionTag.PARTICIPATE_RITUAL,
        need: NeedTag.BELONGING,
        costEnergy: -0.2,
        costTime: 2,
        rewardSatisfaction: 0.7,
        rewardSecondary: { SPIRIT: 0.4, TRADITION: 0.5 },
        socialImpact: { COHESION: 0.4 },
    },
    {
        tag: BelongingActionTag.SHARE_MEAL,
        need: NeedTag.BELONGING,
        costEnergy: -0.05,
        costTime: 1,
        rewardSatisfaction: 0.5,
        rewardSecondary: { AFFECTION: 0.3, TRUST: 0.2 },
        tradeEffect: { spend_food: -1, note: 'shared' },
        socialImpact: { WARMTH: 0.3 },
    },
    {
        tag: BelongingActionTag.HELP_WITH_TASK,
        need: NeedTag.BELONGING,
        costEnergy: -0.3,
        costTime: 2,
        rewardSatisfaction: 0.6,
        rewardSecondary: { LOYALTY: 0.4, RESPECT: 0.2 },
        socialImpact: { GRATITUDE: 0.4 },
    },
    {
        tag: BelongingActionTag.GIFT_TO_MEMBER,
        need: NeedTag.BELONGING,
        costEnergy: -0.1,
        costTime: 0.5,
        rewardSatisfaction: 0.5,
        rewardSecondary: { AFFECTION: 0.4, TRUST: 0.3 },
        tradeEffect: { give_item: 'gift', note: 'bonding' },
        socialImpact: { RECIPROCITY: 0.3 },
    },
    {
        tag: BelongingActionTag.WEAR_SYMBOLS,
        need: NeedTag.BELONGING,
        costEnergy: -0.02,
        costTime: 0.2,
        rewardSatisfaction: 0.3,
        rewardSecondary: { STATUS: 0.2, TRADITION: 0.2 },
        socialImpact: { IN_GROUP: 0.3, OUT_GROUP: -0.1 },
    },
    {
        tag: BelongingActionTag.SING_CHANT,
        need: NeedTag.BELONGING,
        costEnergy: -0.1,
        costTime: 0.8,
        rewardSatisfaction: 0.5,
        rewardSecondary: { MOOD: 0.4, COMMUNITY: 0.4 },
        socialImpact: { COHESION: 0.4 },
    },
    {
        tag: BelongingActionTag.DEFEND_MEMBER,
        need: NeedTag.BELONGING,
        costEnergy: -0.5,
        costTime: 1,
        rewardSatisfaction: 0.8,
        risk: 0.3,
        rewardSecondary: { LOYALTY: 0.6, HONOR: 0.4 },
        socialImpact: { RESPECT: 0.4, TRUST: 0.3 },
    },
    {
        tag: BelongingActionTag.HOST_GUESTS,
        need: NeedTag.BELONGING,
        costEnergy: -0.2,
        costTime: 2,
        rewardSatisfaction: 0.6,
        rewardSecondary: { STATUS: 0.2, COMMUNITY: 0.5 },
        tradeEffect: { spend_food: -2, spend_time: 'hospitality' },
        socialImpact: { GRATITUDE: 0.5 },
    },
    {
        tag: BelongingActionTag.BUILD_COMMON_SPACE,
        need: NeedTag.BELONGING,
        costEnergy: -0.6,
        costTime: 4,
        rewardSatisfaction: 0.9,
        rewardSecondary: { COMMUNITY: 0.6, STABILITY: 0.5 },
        socialImpact: { LEGACY: 0.3 },
    },
    {
        tag: BelongingActionTag.CELEBRATE_HOLIDAY,
        need: NeedTag.BELONGING,
        costEnergy: -0.2,
        costTime: 3,
        rewardSatisfaction: 0.7,
        rewardSecondary: { TRADITION: 0.6, MOOD: 0.5 },
        socialImpact: { COHESION: 0.5 },
    },
    {
        tag: BelongingActionTag.MOURN_TOGETHER,
        need: NeedTag.BELONGING,
        costEnergy: -0.2,
        costTime: 2,
        rewardSatisfaction: 0.6,
        rewardSecondary: { AFFECTION: 0.5, SPIRIT: 0.3 },
        socialImpact: { EMPATHY: 0.5 },
    },
    {
        tag: BelongingActionTag.TELL_STORIES,
        need: NeedTag.BELONGING,
        costEnergy: -0.05,
        costTime: 1,
        rewardSatisfaction: 0.5,
        rewardSecondary: { TRADITION: 0.4, KNOWLEDGE: 0.3 },
        socialImpact: { IDENTITY: 0.4 },
    },
    {
        tag: BelongingActionTag.TRAIN_TOGETHER,
        need: NeedTag.BELONGING,
        costEnergy: -0.3,
        costTime: 2,
        rewardSatisfaction: 0.6,
        rewardSecondary: { MASTERY: 0.4, TRUST: 0.3 },
        socialImpact: { TEAMWORK: 0.5 },
    },
    {
        tag: BelongingActionTag.MEDIATE_DISPUTE,
        need: NeedTag.BELONGING,
        costEnergy: -0.2,
        costTime: 1.5,
        rewardSatisfaction: 0.7,
        rewardSecondary: { COMMUNITY: 0.5, STABILITY: 0.4 },
        socialImpact: { HARMONY: 0.5 },
    },
];
