import { ActionDefinition } from '../action-definition';
import { ComfortActionTag } from '../action-tags';
import { NeedTag } from '../needs';

export const ComfortActions: ActionDefinition[] = [
  {
    tag: ComfortActionTag.LIGHT_FIRE,
    need: NeedTag.COMFORT,
    costEnergy: -0.4,
    costTime: 1,
    rewardSatisfaction: 0.8,
    rewardSecondary: { SECURITY: 0.3, HEALTH: 0.2 },
    requiresItem: ['wood', 'flint'],
    requiresLocation: 'camp',
    temperatureEffect: +10,
  },
  {
    tag: ComfortActionTag.SIT_BY_FIRE,
    need: NeedTag.COMFORT,
    costEnergy: -0.05,
    costTime: 1,
    rewardSatisfaction: 0.7,
    rewardSecondary: { MOOD: 0.4, REST: 0.3 },
    requiresLocation: 'campfire',
    temperatureEffect: +5,
  },
  {
    tag: ComfortActionTag.ENTER_SHELTER,
    need: NeedTag.COMFORT,
    costEnergy: -0.1,
    costTime: 0.2,
    rewardSatisfaction: 0.5,
    rewardSecondary: { STABILITY: 0.3, SECURITY: 0.2 },
    requiresLocation: 'shelter',
  },
  {
    tag: ComfortActionTag.COVER_WITH_FUR,
    need: NeedTag.COMFORT,
    costEnergy: -0.05,
    costTime: 0.2,
    rewardSatisfaction: 0.4,
    rewardSecondary: { HEALTH: 0.2 },
    requiresItem: ['fur'],
    temperatureEffect: +3,
  },
  {
    tag: ComfortActionTag.DRINK_HOT_BEVERAGE,
    need: NeedTag.COMFORT,
    costEnergy: -0.05,
    costTime: 0.5,
    rewardSatisfaction: 0.6,
    rewardSecondary: { MOOD: 0.4, HEALTH: 0.2 },
    requiresItem: ['hot_drink'],
  },
  {
    tag: ComfortActionTag.BUILD_BED,
    need: NeedTag.COMFORT,
    costEnergy: -0.6,
    costTime: 3,
    rewardSatisfaction: 0.9,
    rewardSecondary: { REST: 0.6, STABILITY: 0.4 },
    requiresItem: ['straw', 'wood'],
    requiresLocation: 'home',
  },
  {
    tag: ComfortActionTag.REPAIR_HOUSE,
    need: NeedTag.COMFORT,
    costEnergy: -0.5,
    costTime: 4,
    rewardSatisfaction: 0.7,
    rewardSecondary: { STABILITY: 0.6, SECURITY: 0.4 },
    requiresItem: ['wood', 'clay'],
    requiresLocation: 'home',
  },
  {
    tag: ComfortActionTag.SNUGGLE_WITH_PARTNER,
    need: NeedTag.COMFORT,
    costEnergy: -0.1,
    costTime: 1,
    rewardSatisfaction: 0.8,
    rewardSecondary: { AFFECTION: 0.5, MOOD: 0.3 },
    requiresLocation: 'home',
    targetType: 'OTHER',
  },
  {
    tag: ComfortActionTag.DECORATE_HOME,
    need: NeedTag.COMFORT,
    costEnergy: -0.3,
    costTime: 2,
    rewardSatisfaction: 0.5,
    rewardSecondary: { STATUS: 0.2, MOOD: 0.3 },
    requiresItem: ['paint', 'fabric'],
  },
  {
    tag: ComfortActionTag.BASK_IN_SUN,
    need: NeedTag.COMFORT,
    costEnergy: 0,
    costTime: 1,
    rewardSatisfaction: 0.4,
    rewardSecondary: { MOOD: 0.3, HEALTH: 0.2 },
    requiresLocation: 'outdoors',
    temperatureEffect: +2,
  },
];
