import { ActionDefinition } from '../action-definition';
import { ActionTags } from '../action-tags';
import { NeedTag } from '../needs';

export const FoodActions: ActionDefinition[] = [
  {
    tag: ActionTags.FORAGE,
    need: NeedTag.FOOD,
    costEnergy: 0.2,
    costTime: 3,
    risk: 0.1,
    rewardSatisfaction: 0.4,
    rewardSecondary: { CURIOSITY: 0.1 },
    socialImpact: 0,
    moralWeight: 0,
    groupAffinity: 0,
    skillRequired: 'Survival',
    resourceOutput: ['berries', 'roots'],
    locationType: 'wilderness',
    emotionalImpact: 0.1,
    environmentalImpact: -0.1,
  },
  {
    tag: ActionTags.HUNT,
    need: NeedTag.FOOD,
    costEnergy: 0.5,
    costTime: 5,
    risk: 0.4,
    rewardSatisfaction: 0.8,
    rewardSecondary: { STATUS: 0.2, WEALTH: 0.1 },
    socialImpact: 0.1,
    moralWeight: 0.3,
    groupAffinity: 0.2,
    skillRequired: 'Hunting',
    resourceOutput: ['meat', 'hide'],
    locationType: 'wilderness',
    respectGain: 0.3,
    emotionalImpact: 0.2,
  },
  {
    tag: ActionTags.STEAL_FOOD,
    need: NeedTag.FOOD,
    costEnergy: 0.1,
    costTime: 1,
    risk: 0.6,
    rewardSatisfaction: 0.6,
    socialImpact: -0.5,
    moralWeight: -0.8,
    shameGain: 0.3,
    locationType: 'village',
    visibleToOthers: true,
    emotionalImpact: -0.3,
  },
];
