import { ActionDefinition } from '../action-definition';
import { HealthActionTag } from '../action-tags';
import { NeedTag } from '../needs';

export const HealthActions: ActionDefinition[] = [
  {
    tag: HealthActionTag.HEAL_SELF,
    need: NeedTag.HEALTH,
    costEnergy: -0.2,
    costTime: 1.5,
    rewardSatisfaction: 0.6,
    rewardSecondary: { HYGIENE: 0.1, MOOD: 0.2 },
    skillRequired: 'FirstAid',
    locationType: 'any',
    targetType: 'SELF',
  },
  {
    tag: HealthActionTag.HEAL_OTHER,
    need: NeedTag.HEALTH,
    costEnergy: -0.3,
    costTime: 2,
    rewardSatisfaction: 0.8,
    rewardSecondary: { TRUST: 0.3, COMMUNITY: 0.2 },
    skillRequired: 'Medicine',
    targetType: 'OTHER',
    socialImpact: 0.3,
  },
  {
    tag: HealthActionTag.APPLY_BANDAGE,
    need: NeedTag.HEALTH,
    costEnergy: -0.15,
    costTime: 1,
    rewardSatisfaction: 0.4,
    requiresItem: ['bandage'],
    locationType: 'any',
    skillRequired: 'FirstAid',
  },
  {
    tag: HealthActionTag.CLEAN_WOUND,
    need: NeedTag.HEALTH,
    costEnergy: -0.1,
    costTime: 0.5,
    rewardSatisfaction: 0.3,
    requiresItem: ['clean_water'],
    rewardSecondary: { HYGIENE: 0.3 },
  },
  {
    tag: HealthActionTag.APPLY_HERBAL_REMEDY,
    need: NeedTag.HEALTH,
    costEnergy: -0.2,
    costTime: 2,
    rewardSatisfaction: 0.7,
    requiresItem: ['herbs'],
    skillRequired: 'Herbalism',
    rewardSecondary: { SPIRIT: 0.1 },
  },
  {
    tag: HealthActionTag.DRINK_MEDICINE,
    need: NeedTag.HEALTH,
    costEnergy: -0.05,
    costTime: 0.2,
    rewardSatisfaction: 0.5,
    requiresItem: ['medicine'],
    rewardSecondary: { MOOD: 0.2 },
  },
  {
    tag: HealthActionTag.REST_FOR_RECOVERY,
    need: NeedTag.HEALTH,
    costEnergy: -0.3,
    costTime: 6,
    rewardSatisfaction: 1.0,
    rewardSecondary: { REST: 0.6, MOOD: 0.3 },
    locationType: 'bed',
  },
  {
    tag: HealthActionTag.SEEK_HEALER,
    need: NeedTag.HEALTH,
    costEnergy: -0.4,
    costTime: 3,
    rewardSatisfaction: 0.7,
    rewardSecondary: { TRUST: 0.2 },
    targetType: 'OTHER',
    locationType: 'village',
  },
  {
    tag: HealthActionTag.PRAY_FOR_HEALTH,
    need: NeedTag.HEALTH,
    costEnergy: -0.1,
    costTime: 1,
    rewardSatisfaction: 0.4,
    rewardSecondary: { SPIRIT: 0.3, MOOD: 0.2 },
    locationType: 'temple',
  },
  {
    tag: HealthActionTag.PERFORM_RITUAL_HEALING,
    need: NeedTag.HEALTH,
    costEnergy: -0.2,
    costTime: 3,
    rewardSatisfaction: 0.8,
    rewardSecondary: { SPIRIT: 0.6, COMMUNITY: 0.4 },
    skillRequired: 'Ritualism',
    locationType: 'sacred_site',
  },
  {
    tag: HealthActionTag.CLEAN_BODY,
    need: NeedTag.HEALTH,
    costEnergy: -0.15,
    costTime: 1,
    rewardSatisfaction: 0.3,
    rewardSecondary: { HYGIENE: 0.5 },
    locationType: 'river',
  },
  {
    tag: HealthActionTag.EAT_HEALTHY_MEAL,
    need: NeedTag.HEALTH,
    costEnergy: -0.05,
    costTime: 0.5,
    rewardSatisfaction: 0.3,
    rewardSecondary: { FOOD: 0.5, MOOD: 0.2 },
    requiresItem: ['meal_healthy'],
  },
  {
    tag: HealthActionTag.ISOLATE_SELF,
    need: NeedTag.HEALTH,
    costEnergy: -0.2,
    costTime: 4,
    risk: 0.1,
    rewardSatisfaction: 0.4,
    rewardSecondary: { COMMUNITY: -0.1 },
    locationType: 'hut',
  },
  {
    tag: HealthActionTag.MASSAGE,
    need: NeedTag.HEALTH,
    costEnergy: -0.15,
    costTime: 1.5,
    rewardSatisfaction: 0.5,
    rewardSecondary: { REST: 0.4, AFFECTION: 0.3 },
    targetType: 'SELF',
  },
  {
    tag: HealthActionTag.CHECK_HEALTH,
    need: NeedTag.HEALTH,
    costEnergy: -0.05,
    costTime: 0.5,
    rewardSatisfaction: 0.2,
    rewardSecondary: { KNOWLEDGE: 0.1 },
    skillRequired: 'Medicine',
  },
  {
    tag: HealthActionTag.MAKE_MEDICINE,
    need: NeedTag.HEALTH,
    costEnergy: -0.25,
    costTime: 2.5,
    rewardSatisfaction: 0.6,
    rewardSecondary: { KNOWLEDGE: 0.3 },
    requiresItem: ['herbs', 'water'],
    skillRequired: 'Alchemy',
  },
];
