import { ActionDefinition } from '../action-definition';
import { HygieneActionTag } from '../action-tags';
import { NeedTag } from '../needs';

export const HygieneActions: ActionDefinition[] = [
  {
    tag: HygieneActionTag.WASH_HANDS,
    need: NeedTag.HYGIENE,
    costEnergy: -0.05,
    costTime: 0.2,
    rewardSatisfaction: 0.3,
    rewardSecondary: { HEALTH: 0.2 },
    requiresItem: ['water'],
    requiresLocation: 'home',
  },
  {
    tag: HygieneActionTag.BATHE_IN_RIVER,
    need: NeedTag.HYGIENE,
    costEnergy: -0.3,
    costTime: 1,
    rewardSatisfaction: 0.7,
    rewardSecondary: { HEALTH: 0.3, MOOD: 0.4 },
    risk: 0.1,
    requiresLocation: 'river',
  },
  {
    tag: HygieneActionTag.TAKE_BATH,
    need: NeedTag.HYGIENE,
    costEnergy: -0.4,
    costTime: 1.5,
    rewardSatisfaction: 0.9,
    rewardSecondary: { HEALTH: 0.4, SOCIAL: 0.3 },
    requiresItem: ['hot_water', 'soap'],
    requiresLocation: 'bathhouse',
  },
  {
    tag: HygieneActionTag.CLEAN_BODY_WITH_ASH,
    need: NeedTag.HYGIENE,
    costEnergy: -0.2,
    costTime: 0.7,
    rewardSatisfaction: 0.6,
    rewardSecondary: { HEALTH: 0.2 },
    requiresItem: ['ash', 'cloth'],
  },
  {
    tag: HygieneActionTag.CLEAN_CLOTHES,
    need: NeedTag.HYGIENE,
    costEnergy: -0.5,
    costTime: 2,
    rewardSatisfaction: 0.8,
    rewardSecondary: { SOCIAL: 0.3 },
    requiresItem: ['soap', 'water'],
    requiresLocation: 'river',
  },
  {
    tag: HygieneActionTag.APPLY_SCENT,
    need: NeedTag.HYGIENE,
    costEnergy: -0.05,
    costTime: 0.3,
    rewardSatisfaction: 0.4,
    rewardSecondary: { RESPECT: 0.3, SOCIAL: 0.2 },
    requiresItem: ['perfume', 'oil'],
  },
  {
    tag: HygieneActionTag.CLEAN_HOME,
    need: NeedTag.HYGIENE,
    costEnergy: -0.5,
    costTime: 3,
    rewardSatisfaction: 0.7,
    rewardSecondary: { HEALTH: 0.4, STABILITY: 0.3 },
    requiresLocation: 'home',
  },
  {
    tag: HygieneActionTag.DISPOSE_WASTE,
    need: NeedTag.HYGIENE,
    costEnergy: -0.4,
    costTime: 2,
    rewardSatisfaction: 0.6,
    rewardSecondary: { HEALTH: 0.5 },
    requiresLocation: 'settlement',
  },
  {
    tag: HygieneActionTag.CLEAN_WOUNDS,
    need: NeedTag.HYGIENE,
    costEnergy: -0.3,
    costTime: 1,
    rewardSatisfaction: 0.5,
    rewardSecondary: { HEALTH: 0.6 },
    requiresItem: ['water', 'cloth'],
  },
  {
    tag: HygieneActionTag.RITUAL_CLEANSING,
    need: NeedTag.HYGIENE,
    costEnergy: -0.4,
    costTime: 1.5,
    rewardSatisfaction: 0.8,
    rewardSecondary: { SPIRIT: 0.5, SOCIAL: 0.3 },
    requiresLocation: 'temple',
    moralWeight: 0.5,
  },
];
