import { ActionDefinition } from '../action-definition';
import { JusticeActionTag } from '../action-tags';
import { NeedTag } from '../needs';

export const JusticeActions: ActionDefinition[] = [
    {
        tag: JusticeActionTag.ACCUSE_OFFENDER,
        need: NeedTag.JUSTICE,
        costEnergy: -0.1,
        costTime: 0.5,
        risk: 0.2, // риск ответной клеветы/конфликта
        rewardSatisfaction: 0.4,
        rewardSecondary: { LAW: 0.3, TRUST: 0.2 },
        requiresSkill: 'Oratory',
        targetType: 'OTHER',
        socialImpact: { respect: +0.2 },
        requiresLocation: 'assembly',
    },
    {
        tag: JusticeActionTag.GATHER_EVIDENCE,
        need: NeedTag.JUSTICE,
        costEnergy: -0.3,
        costTime: 2,
        risk: 0.15,
        rewardSatisfaction: 0.6,
        rewardSecondary: { KNOWLEDGE: 0.4, LAW: 0.3 },
        requiresSkill: 'Investigation',
        locationType: 'any',
    },
    {
        tag: JusticeActionTag.TESTIFY,
        need: NeedTag.JUSTICE,
        costEnergy: -0.1,
        costTime: 0.5,
        risk: 0.1,
        rewardSatisfaction: 0.4,
        rewardSecondary: { TRUST: 0.3, COMMUNITY: 0.2 },
        requiresSkill: 'Honesty',
        requiresLocation: 'court',
        visibleToOthers: true,
    },
    {
        tag: JusticeActionTag.DEMAND_RESTITUTION,
        need: NeedTag.JUSTICE,
        costEnergy: -0.1,
        costTime: 0.5,
        risk: 0.2,
        rewardSatisfaction: 0.6,
        rewardSecondary: { CONTROL: 0.2, WEALTH: 0.3 },
        targetType: 'OTHER',
        socialImpact: { respect: +0.1 },
    },
    {
        tag: JusticeActionTag.PAY_BLOOD_PRICE,
        need: NeedTag.JUSTICE,
        costEnergy: -0.1,
        costTime: 0.2,
        rewardSatisfaction: 0.7,
        rewardSecondary: { STABILITY: 0.4, COMMUNITY: 0.3 },
        requiresItem: ['valuables'],
        moralWeight: 0.5,
        socialImpact: { respect: +0.3 },
    },
    {
        tag: JusticeActionTag.PUBLIC_APOLOGY,
        need: NeedTag.JUSTICE,
        costEnergy: -0.05,
        costTime: 0.3,
        risk: 0.05,
        rewardSatisfaction: 0.5,
        rewardSecondary: { RESPECT: 0.3, COMMUNITY: 0.3 },
        moralWeight: 0.4,
        visibleToOthers: true,
        requiresLocation: 'public_square',
    },
    {
        tag: JusticeActionTag.REPUTATION_RESTORATION,
        need: NeedTag.JUSTICE,
        costEnergy: -0.2,
        costTime: 1,
        rewardSatisfaction: 0.8,
        rewardSecondary: { STATUS: 0.4, RESPECT: 0.5 },
        requiresSkill: 'Diplomacy',
        socialImpact: { respect: +0.4 },
    },
    {
        tag: JusticeActionTag.NEGOTIATE_SETTLEMENT,
        need: NeedTag.JUSTICE,
        costEnergy: -0.2,
        costTime: 1.5,
        risk: 0.15,
        rewardSatisfaction: 0.7,
        rewardSecondary: { STABILITY: 0.5, COMMUNITY: 0.4 },
        requiresSkill: 'Negotiation',
        targetType: 'GROUP',
    },
    {
        tag: JusticeActionTag.MEDIATE_REPARATION,
        need: NeedTag.JUSTICE,
        costEnergy: -0.2,
        costTime: 1.5,
        rewardSatisfaction: 0.6,
        rewardSecondary: { TRUST: 0.4, LAW: 0.3 },
        requiresSkill: 'Mediation',
        targetType: 'GROUP',
    },
    {
        tag: JusticeActionTag.SHUN_OFFENDER,
        need: NeedTag.JUSTICE,
        costEnergy: -0.05,
        costTime: 0.2,
        risk: 0.1,
        rewardSatisfaction: 0.5,
        rewardSecondary: { COMMUNITY: 0.3, CONTROL: 0.2 },
        moralWeight: 0.2,
        socialImpact: { respect: +0.3 },
        targetType: 'OTHER',
    },
    {
        tag: JusticeActionTag.CURSE_OFFENDER,
        need: NeedTag.JUSTICE,
        costEnergy: -0.1,
        costTime: 0.5,
        rewardSatisfaction: 0.6,
        rewardSecondary: { SPIRIT: 0.4, COMMUNITY: 0.2 },
        requiresSkill: 'Ritualism',
        requiresLocation: 'temple',
        moralWeight: 0.3,
    },
    {
        tag: JusticeActionTag.DUEL_OF_HONOR,
        need: NeedTag.JUSTICE,
        costEnergy: -0.6,
        costTime: 1,
        risk: 0.6, // высокий риск
        rewardSatisfaction: 0.9,
        rewardSecondary: { HONOR: 0.6, STATUS: 0.4 },
        requiresItem: ['weapon'],
        requiresSkill: 'Combat',
        targetType: 'OTHER',
    },
    {
        tag: JusticeActionTag.APPEAL_VERDICT,
        need: NeedTag.JUSTICE,
        costEnergy: -0.2,
        costTime: 1,
        risk: 0.1,
        rewardSatisfaction: 0.5,
        rewardSecondary: { LAW: 0.4, TRUST: 0.2 },
        requiresSkill: 'Rhetoric',
        requiresLocation: 'council_hall',
    },
    {
        tag: JusticeActionTag.REDEEM_OFFENDER,
        need: NeedTag.JUSTICE,
        costEnergy: -0.3,
        costTime: 2,
        rewardSatisfaction: 0.7,
        rewardSecondary: { COMMUNITY: 0.4, LOYALTY: 0.3 },
        requiresSkill: 'Leadership',
        targetType: 'OTHER',
    },
    {
        tag: JusticeActionTag.PLEDGE_NO_REVENGE,
        need: NeedTag.JUSTICE,
        costEnergy: -0.05,
        costTime: 0.2,
        rewardSatisfaction: 0.4,
        rewardSecondary: { STABILITY: 0.3, TRUST: 0.3 },
        requiresLocation: 'temple',
        moralWeight: 0.4,
    },
    {
        tag: JusticeActionTag.VOW_REVENGE,
        need: NeedTag.JUSTICE,
        costEnergy: -0.1,
        costTime: 0.2,
        risk: 0.4, // может породить эскалацию
        rewardSatisfaction: 0.6,
        rewardSecondary: { POWER: 0.2 },
        moralWeight: -0.3,
        emotionalImpact: -0.1,
    },
];
