import { ActionDefinition } from '../action-definition';
import { PropertyActionTag } from '../action-tags';
import { NeedTag } from '../needs';

export const PropertyActions: ActionDefinition[] = [
    {
        tag: PropertyActionTag.CLAIM_LAND,
        need: NeedTag.PROPERTY,
        costEnergy: -0.5,
        costTime: 2,
        rewardSatisfaction: 0.9,
        rewardSecondary: { CONTROL: 0.6, STATUS: 0.4 },
        requiresSkill: 'leadership',
        requiresLocation: 'territory',
        ownershipEffect: { gain: 'land' },
        socialImpact: { respect: +0.3, conflict: +0.2 },
    },
    {
        tag: PropertyActionTag.BUILD_HOUSE,
        need: NeedTag.PROPERTY,
        costEnergy: -0.8,
        costTime: 6,
        rewardSatisfaction: 1.0,
        rewardSecondary: { STABILITY: 0.5, COMFORT: 0.4 },
        requiresItem: ['wood', 'clay'],
        requiresSkill: 'construction',
        ownershipEffect: { gain: 'house' },
    },
    {
        tag: PropertyActionTag.MARK_TERRITORY,
        need: NeedTag.PROPERTY,
        costEnergy: -0.2,
        costTime: 1,
        rewardSatisfaction: 0.6,
        rewardSecondary: { CONTROL: 0.3 },
        requiresItem: ['marker', 'paint', 'rope'],
    },
    {
        tag: PropertyActionTag.DEFEND_PROPERTY,
        need: NeedTag.PROPERTY,
        costEnergy: -0.5,
        costTime: 2,
        rewardSatisfaction: 0.7,
        rewardSecondary: { SECURITY: 0.6, STATUS: 0.2 },
        requiresItem: ['weapon'],
        requiresSkill: 'combat',
        risk: 0.4,
    },
    {
        tag: PropertyActionTag.REPAIR_PROPERTY,
        need: NeedTag.PROPERTY,
        costEnergy: -0.4,
        costTime: 2,
        rewardSatisfaction: 0.6,
        rewardSecondary: { STABILITY: 0.5 },
        requiresItem: ['wood', 'tools'],
        requiresSkill: 'crafting',
    },
    {
        tag: PropertyActionTag.RENT_PROPERTY,
        need: NeedTag.PROPERTY,
        costEnergy: -0.1,
        costTime: 1,
        rewardSatisfaction: 0.5,
        rewardSecondary: { WEALTH: 0.6, STATUS: 0.3 },
        requiresSkill: 'negotiation',
        targetType: 'OTHER',
        ownershipEffect: { partialControl: true },
    },
    {
        tag: PropertyActionTag.TRANSFER_OWNERSHIP,
        need: NeedTag.PROPERTY,
        costEnergy: -0.2,
        costTime: 2,
        rewardSatisfaction: 0.6,
        rewardSecondary: { TRUST: 0.4, STABILITY: 0.3 },
        targetType: 'OTHER',
        ownershipEffect: { transfer: true },
    },
    {
        tag: PropertyActionTag.CONTEST_PROPERTY,
        need: NeedTag.PROPERTY,
        costEnergy: -0.6,
        costTime: 3,
        rewardSatisfaction: 0.8,
        rewardSecondary: { STATUS: 0.4, CONTROL: 0.5 },
        requiresSkill: 'diplomacy',
        risk: 0.3,
    },
    {
        tag: PropertyActionTag.EVICT_INTRUDER,
        need: NeedTag.PROPERTY,
        costEnergy: -0.4,
        costTime: 1,
        rewardSatisfaction: 0.7,
        rewardSecondary: { SECURITY: 0.5, CONTROL: 0.4 },
        requiresSkill: 'intimidation',
        targetType: 'OTHER',
        risk: 0.2,
    },
    {
        tag: PropertyActionTag.STORE_ITEMS,
        need: NeedTag.PROPERTY,
        costEnergy: -0.1,
        costTime: 0.5,
        rewardSatisfaction: 0.4,
        rewardSecondary: { STABILITY: 0.3 },
        requiresLocation: 'home',
    },
];
