import { ActionDefinition } from '../action-definition';
import { ReproductionActionTag } from '../action-tags';
import { NeedTag } from '../needs';

export const ReproductionActions: ActionDefinition[] = [
  {
    tag: ReproductionActionTag.SEEK_PARTNER,
    need: NeedTag.REPRODUCTION,
    costEnergy: -0.3,
    costTime: 2,
    rewardSatisfaction: 0.5,
    rewardSecondary: { SOCIAL: 0.4, MOOD: 0.3 },
    skillRequired: 'Charm',
    locationType: 'community',
  },
  {
    tag: ReproductionActionTag.FLIRT,
    need: NeedTag.REPRODUCTION,
    costEnergy: -0.1,
    costTime: 0.5,
    rewardSatisfaction: 0.3,
    rewardSecondary: { MOOD: 0.4, SOCIAL: 0.2 },
    skillRequired: 'Empathy',
    targetType: 'OTHER',
  },
  {
    tag: ReproductionActionTag.GIFT_TO_PARTNER,
    need: NeedTag.REPRODUCTION,
    costEnergy: -0.15,
    costTime: 0.5,
    rewardSatisfaction: 0.4,
    rewardSecondary: { TRUST: 0.3, MOOD: 0.2 },
    requiresItem: ['gift'],
    targetType: 'OTHER',
  },
  {
    tag: ReproductionActionTag.COURTSHIP_RITUAL,
    need: NeedTag.REPRODUCTION,
    costEnergy: -0.4,
    costTime: 3,
    rewardSatisfaction: 0.6,
    rewardSecondary: { SOCIAL: 0.5, SPIRIT: 0.3 },
    locationType: 'ritual_site',
  },
  {
    tag: ReproductionActionTag.SHOW_STRENGTH,
    need: NeedTag.REPRODUCTION,
    costEnergy: -0.3,
    costTime: 1,
    rewardSatisfaction: 0.4,
    rewardSecondary: { STATUS: 0.3 },
    skillRequired: 'Athletics',
  },
  {
    tag: ReproductionActionTag.BUILD_HOME_FOR_FAMILY,
    need: NeedTag.REPRODUCTION,
    costEnergy: -0.6,
    costTime: 6,
    rewardSatisfaction: 0.8,
    rewardSecondary: { SECURITY: 0.5, STATUS: 0.3 },
    locationType: 'settlement',
  },
  {
    tag: ReproductionActionTag.FORM_UNION,
    need: NeedTag.REPRODUCTION,
    costEnergy: -0.2,
    costTime: 2,
    rewardSatisfaction: 0.7,
    rewardSecondary: { LOVE: 0.8, SOCIAL: 0.4 },
    locationType: 'community',
    targetType: 'OTHER',
    moralWeight: 0.3,
  },
  {
    tag: ReproductionActionTag.MAKE_LOVE,
    need: NeedTag.REPRODUCTION,
    costEnergy: -0.5,
    costTime: 1.5,
    rewardSatisfaction: 1.0,
    rewardSecondary: { LOVE: 0.6, MOOD: 0.3 },
    targetType: 'OTHER',
  },
  {
    tag: ReproductionActionTag.ATTEMPT_CONCEPTION,
    need: NeedTag.REPRODUCTION,
    costEnergy: -0.6,
    costTime: 1.5,
    rewardSatisfaction: 1.2,
    rewardSecondary: { FAMILY: 0.6 },
    targetType: 'OTHER',
    risk: 0.3,
  },
  {
    tag: ReproductionActionTag.CARE_FOR_PARTNER,
    need: NeedTag.REPRODUCTION,
    costEnergy: -0.2,
    costTime: 1,
    rewardSatisfaction: 0.5,
    rewardSecondary: { LOVE: 0.4, TRUST: 0.3 },
    targetType: 'OTHER',
  },
  {
    tag: ReproductionActionTag.CARE_FOR_CHILD,
    need: NeedTag.REPRODUCTION,
    costEnergy: -0.4,
    costTime: 3,
    rewardSatisfaction: 0.8,
    rewardSecondary: { LOVE: 0.6, FAMILY: 0.8 },
    targetType: 'FAMILY',
  },
  {
    tag: ReproductionActionTag.TEACH_CHILD,
    need: NeedTag.REPRODUCTION,
    costEnergy: -0.3,
    costTime: 2,
    rewardSatisfaction: 0.6,
    rewardSecondary: { KNOWLEDGE: 0.5, FAMILY: 0.5 },
    targetType: 'FAMILY',
  },
  {
    tag: ReproductionActionTag.CELEBRATE_FERTILITY,
    need: NeedTag.REPRODUCTION,
    costEnergy: -0.3,
    costTime: 2.5,
    rewardSatisfaction: 0.7,
    rewardSecondary: { SPIRIT: 0.5, SOCIAL: 0.4 },
    locationType: 'ritual_site',
  },
  {
    tag: ReproductionActionTag.DEFEND_FAMILY,
    need: NeedTag.REPRODUCTION,
    costEnergy: -0.6,
    costTime: 1.5,
    rewardSatisfaction: 0.7,
    rewardSecondary: { SECURITY: 0.8, HONOR: 0.5 },
    risk: 0.4,
    locationType: 'home',
  },
  {
    tag: ReproductionActionTag.SEEK_MIDWIFE,
    need: NeedTag.REPRODUCTION,
    costEnergy: -0.3,
    costTime: 3,
    rewardSatisfaction: 0.6,
    rewardSecondary: { HEALTH: 0.5, FAMILY: 0.4 },
    targetType: 'OTHER',
  },
  {
    tag: ReproductionActionTag.BLESS_CHILD,
    need: NeedTag.REPRODUCTION,
    costEnergy: -0.1,
    costTime: 1,
    rewardSatisfaction: 0.5,
    rewardSecondary: { SPIRIT: 0.6, FAMILY: 0.4 },
    locationType: 'temple',
  },
];
