import { ActionDefinition } from '../action-definition';
import { SecurityActionTag } from '../action-tags';
import { NeedTag } from '../needs';

export const SecurityActions: ActionDefinition[] = [
    {
        tag: SecurityActionTag.BUILD_SHELTER,
        need: NeedTag.SECURITY,
        costEnergy: -0.6,
        costTime: 4,
        rewardSatisfaction: 0.9,
        rewardSecondary: { COMFORT: 0.5, STABILITY: 0.4 },
        requiresItem: ['wood', 'branches', 'clay'],
        requiresSkill: 'construction',
        targetType: 'AREA',
    },
    {
        tag: SecurityActionTag.FORTIFY_WALLS,
        need: NeedTag.SECURITY,
        costEnergy: -0.7,
        costTime: 5,
        rewardSatisfaction: 0.8,
        rewardSecondary: { STABILITY: 0.6, CONTROL: 0.3 },
        requiresItem: ['wood', 'stone'],
        requiresLocation: 'settlement',
        requiresSkill: 'engineering',
    },
    {
        tag: SecurityActionTag.SET_TRAPS,
        need: NeedTag.SECURITY,
        costEnergy: -0.3,
        costTime: 2,
        rewardSatisfaction: 0.6,
        rewardSecondary: { CONTROL: 0.2 },
        requiresItem: ['rope', 'wood'],
        requiresSkill: 'trapping',
    },
    {
        tag: SecurityActionTag.STAND_GUARD,
        need: NeedTag.SECURITY,
        costEnergy: -0.4,
        costTime: 3,
        rewardSatisfaction: 0.5,
        rewardSecondary: { TRUST: 0.4, CONTROL: 0.3 },
        targetType: 'GROUP',
    },
    {
        tag: SecurityActionTag.TRAIN_WITH_WEAPON,
        need: NeedTag.SECURITY,
        costEnergy: -0.5,
        costTime: 2,
        rewardSatisfaction: 0.5,
        rewardSecondary: { POWER: 0.3, MASTERY: 0.2 },
        requiresItem: ['weapon'],
        requiresSkill: 'combat',
    },
    {
        tag: SecurityActionTag.REPAIR_DEFENSES,
        need: NeedTag.SECURITY,
        costEnergy: -0.6,
        costTime: 3,
        rewardSatisfaction: 0.7,
        rewardSecondary: { STABILITY: 0.4 },
        requiresItem: ['wood', 'stone'],
        requiresLocation: 'settlement',
    },
    {
        tag: SecurityActionTag.PATROL_PERIMETER,
        need: NeedTag.SECURITY,
        costEnergy: -0.4,
        costTime: 2,
        rewardSatisfaction: 0.6,
        rewardSecondary: { CONTROL: 0.4, TRUST: 0.3 },
        requiresSkill: 'scouting',
        targetType: 'AREA',
    },
    {
        tag: SecurityActionTag.HUNT_THREATS,
        need: NeedTag.SECURITY,
        costEnergy: -0.8,
        costTime: 4,
        rewardSatisfaction: 0.8,
        rewardSecondary: { POWER: 0.4, HEALTH: 0.3 },
        risk: 0.4,
        requiresItem: ['weapon'],
        requiresSkill: 'combat',
    },
    {
        tag: SecurityActionTag.WARN_ALLIES,
        need: NeedTag.SECURITY,
        costEnergy: -0.1,
        costTime: 0.2,
        rewardSatisfaction: 0.3,
        rewardSecondary: { TRUST: 0.4, COMMUNITY: 0.3 },
        targetType: 'GROUP',
    },
    {
        tag: SecurityActionTag.SEEK_SHELTER,
        need: NeedTag.SECURITY,
        costEnergy: -0.2,
        costTime: 0.5,
        rewardSatisfaction: 0.7,
        rewardSecondary: { COMFORT: 0.4, HEALTH: 0.2 },
        requiresLocation: 'shelter',
    },
];
