import { ActionDefinition } from '../action-definition';
import { ActionTags } from '../action-tags';
import { NeedTag } from '../needs';

export const WaterActions: ActionDefinition[] = [
  {
    tag: ActionTags.COLLECT_WATER,
    need: NeedTag.WATER,
    costEnergy: 0.2,
    costTime: 2,
    risk: 0.1,
    rewardSatisfaction: 0.4,
    rewardSecondary: { SECURITY: 0.1 },
    socialImpact: 0,
    moralWeight: 0,
    groupAffinity: 0,
    skillRequired: 'Survival',
    resourceOutput: ['raw_water'],
    locationType: 'riverbank',
    environmentalImpact: -0.05,
  },
  {
    tag: ActionTags.FETCH_WATER,
    need: NeedTag.WATER,
    costEnergy: 0.3,
    costTime: 3,
    risk: 0.05,
    rewardSatisfaction: 0.3,
    rewardSecondary: { FAMILY: 0.1 },
    socialImpact: 0.1,
    moralWeight: 0.1,
    groupAffinity: 0.2,
    resourceInput: ['container'],
    resourceOutput: ['raw_water'],
    locationType: 'village',
    emotionalImpact: 0.1,
  },
  {
    tag: ActionTags.BOIL_WATER,
    need: NeedTag.WATER,
    costEnergy: 0.1,
    costTime: 1,
    risk: 0.02,
    rewardSatisfaction: 0.2,
    rewardSecondary: { HEALTH: 0.3 },
    moralWeight: 0.2,
    skillRequired: 'Cooking',
    resourceInput: ['raw_water', 'fire'],
    resourceOutput: ['clean_water'],
    locationType: 'camp',
  },
  {
    tag: ActionTags.DRINK_WATER,
    need: NeedTag.WATER,
    costEnergy: 0.05,
    costTime: 0.5,
    risk: 0,
    rewardSatisfaction: 1.0,
    moralWeight: 0,
    resourceInput: ['clean_water'],
    locationType: 'any',
    emotionalImpact: 0.3,
  },
  {
    tag: ActionTags.SHARE_WATER,
    need: NeedTag.WATER,
    costEnergy: 0.05,
    costTime: 0.5,
    risk: 0,
    rewardSatisfaction: 0.3,
    rewardSecondary: { AFFECTION: 0.4, RESPECT: 0.2 },
    socialImpact: 0.5,
    moralWeight: 0.6,
    groupAffinity: 0.5,
    resourceInput: ['clean_water'],
    visibleToOthers: true,
  },
  {
    tag: ActionTags.STEAL_WATER,
    need: NeedTag.WATER,
    costEnergy: 0.1,
    costTime: 1,
    risk: 0.6,
    rewardSatisfaction: 0.7,
    socialImpact: -0.6,
    moralWeight: -0.8,
    shameGain: 0.4,
    visibleToOthers: false,
    emotionalImpact: -0.4,
  },
  {
    tag: ActionTags.TRADE_FOR_WATER,
    need: NeedTag.WATER,
    costEnergy: 0.05,
    costTime: 2,
    risk: 0.05,
    rewardSatisfaction: 0.8,
    socialImpact: 0.2,
    moralWeight: 0.3,
    groupAffinity: 0.1,
    resourceInput: ['trade_goods'],
    resourceOutput: ['clean_water'],
    locationType: 'market',
  },
  {
    tag: ActionTags.GUARD_WATER_SOURCE,
    need: NeedTag.WATER,
    costEnergy: 0.2,
    costTime: 4,
    risk: 0.2,
    rewardSatisfaction: 0.1,
    rewardSecondary: { POWER: 0.2, STATUS: 0.3 },
    moralWeight: 0.2,
    socialImpact: 0.1,
    locationType: 'well',
  },
  {
    tag: ActionTags.BUILD_WELL,
    need: NeedTag.WATER,
    costEnergy: 0.6,
    costTime: 12,
    risk: 0.3,
    rewardSatisfaction: 0.8,
    rewardSecondary: { LEGACY: 0.4, COMMUNITY: 0.3 },
    moralWeight: 0.5,
    skillRequired: 'Construction',
    resourceInput: ['stone', 'wood', 'tools'],
    resourceOutput: ['well'],
    locationType: 'village',
  },
  {
    tag: ActionTags.MAINTAIN_WELL,
    need: NeedTag.WATER,
    costEnergy: 0.3,
    costTime: 3,
    risk: 0.1,
    rewardSatisfaction: 0.4,
    rewardSecondary: { COMMUNITY: 0.2 },
    moralWeight: 0.4,
    locationType: 'village',
  },
  {
    tag: ActionTags.DISCOVER_WATER_SOURCE,
    need: NeedTag.WATER,
    costEnergy: 0.5,
    costTime: 6,
    risk: 0.5,
    rewardSatisfaction: 0.7,
    rewardSecondary: { KNOWLEDGE: 0.3, STATUS: 0.2 },
    moralWeight: 0.3,
    locationType: 'wilderness',
    skillRequired: 'Survival',
  },
  {
    tag: ActionTags.RATION_WATER,
    need: NeedTag.WATER,
    costEnergy: 0.1,
    costTime: 1,
    risk: 0,
    rewardSatisfaction: 0.2,
    rewardSecondary: { CONTROL: 0.4, LOYALTY: 0.2 },
    socialImpact: 0.3,
    moralWeight: 0.4,
    locationType: 'camp',
  },
];
