import { ActionDefinition } from '../action-definition';
import { WealthActionTag } from '../action-tags';
import { NeedTag } from '../needs';

export const WealthActions: ActionDefinition[] = [
    {
        tag: WealthActionTag.MINE_RESOURCES,
        need: NeedTag.WEALTH,
        costEnergy: -0.6,
        costTime: 4,
        rewardSatisfaction: 0.8,
        rewardSecondary: { SECURITY: 0.3, STABILITY: 0.2 },
        requiresItem: ['pickaxe'],
        requiresSkill: 'mining',
        requiresLocation: 'mine',
        tradeEffect: { resource: 'ore', amount: +5 },
    },
    {
        tag: WealthActionTag.CRAFT_VALUABLES,
        need: NeedTag.WEALTH,
        costEnergy: -0.5,
        costTime: 3,
        rewardSatisfaction: 0.7,
        rewardSecondary: { STATUS: 0.3, MASTERY: 0.4 },
        requiresSkill: 'crafting',
        requiresItem: ['materials'],
        requiresLocation: 'workshop',
        tradeEffect: { itemValue: +10 },
    },
    {
        tag: WealthActionTag.TRADE_WITH_MERCHANT,
        need: NeedTag.WEALTH,
        costEnergy: -0.3,
        costTime: 2,
        rewardSatisfaction: 0.6,
        rewardSecondary: { TRUST: 0.3, STABILITY: 0.3 },
        requiresSkill: 'bargaining',
        requiresLocation: 'market',
        targetType: 'MARKET',
        tradeEffect: { balance: +5 },
    },
    {
        tag: WealthActionTag.STORE_WEALTH,
        need: NeedTag.WEALTH,
        costEnergy: -0.1,
        costTime: 0.5,
        rewardSatisfaction: 0.4,
        rewardSecondary: { SECURITY: 0.4 },
        requiresLocation: 'home',
    },
    {
        tag: WealthActionTag.COLLECT_TAX,
        need: NeedTag.WEALTH,
        costEnergy: -0.4,
        costTime: 2,
        rewardSatisfaction: 0.8,
        rewardSecondary: { CONTROL: 0.6, STATUS: 0.3 },
        requiresSkill: 'leadership',
        targetType: 'GROUP',
        tradeEffect: { balance: +10 },
    },
    {
        tag: WealthActionTag.HIRE_WORKERS,
        need: NeedTag.WEALTH,
        costEnergy: -0.2,
        costTime: 1,
        rewardSatisfaction: 0.5,
        rewardSecondary: { CONTROL: 0.4, STATUS: 0.3 },
        requiresSkill: 'management',
        requiresItem: ['money'],
        targetType: 'OTHER',
    },
    {
        tag: WealthActionTag.LEND_RESOURCES,
        need: NeedTag.WEALTH,
        costEnergy: -0.1,
        costTime: 1,
        rewardSatisfaction: 0.4,
        rewardSecondary: { TRUST: 0.5, COMMUNITY: 0.2 },
        requiresItem: ['money'],
        tradeEffect: { balance: -5 },
    },
    {
        tag: WealthActionTag.DEMAND_PAYMENT,
        need: NeedTag.WEALTH,
        costEnergy: -0.2,
        costTime: 1,
        rewardSatisfaction: 0.6,
        rewardSecondary: { CONTROL: 0.3 },
        requiresSkill: 'intimidation',
        targetType: 'OTHER',
        risk: 0.2,
    },
    {
        tag: WealthActionTag.DONATE_WEALTH,
        need: NeedTag.WEALTH,
        costEnergy: -0.2,
        costTime: 1,
        rewardSatisfaction: 0.5,
        rewardSecondary: { RESPECT: 0.6, SPIRIT: 0.3 },
        requiresItem: ['money'],
        tradeEffect: { balance: -5 },
    },
    {
        tag: WealthActionTag.SHOW_OFF_WEALTH,
        need: NeedTag.WEALTH,
        costEnergy: -0.1,
        costTime: 0.5,
        rewardSatisfaction: 0.5,
        rewardSecondary: { STATUS: 0.6, RESPECT: 0.4 },
        requiresItem: ['jewelry', 'clothing'],
        socialImpact: { admiration: +0.3, envy: +0.2 },
    },
];
