import { ActionDefinition } from '../action-definition';
import { AccountabilityActionTag } from '../action-tags';
import { NeedTag } from '../needs';

export const AccountabilityActions: ActionDefinition[] = [
    {
        tag: AccountabilityActionTag.DUTY_CHART_POST,
        need: NeedTag.ACCOUNTABILITY,
        costEnergy: -0.08,
        costTime: 0.9,
        rewardSatisfaction: 0.65,
        rewardSecondary: { CLARITY: 0.5, ORDER: 0.4, TRUST: 0.3 },
        tradeEffect: { parchment: -1, ink: -1 },
        ownershipEffect: { roleMatrix: 'posted_named_owners' },
        lawEffect: { dutyCharter: 'ratified', enforceable: true },
    },
    {
        tag: AccountabilityActionTag.PERSONAL_WEEKLY_REPORT,
        need: NeedTag.ACCOUNTABILITY,
        costEnergy: -0.1,
        costTime: 1.0,
        rewardSatisfaction: 0.7,
        rewardSecondary: { INTEGRITY: 0.4, TRUST: 0.3, CLARITY: 0.3 },
        tradeEffect: { parchment: -1, ink: -1 },
        ownershipEffect: { worklog: 'weekly_summary_posted' },
    },
    {
        tag: AccountabilityActionTag.TASK_HANDOFF_FORMALIZE,
        need: NeedTag.ACCOUNTABILITY,
        costEnergy: -0.08,
        costTime: 0.8,
        rewardSatisfaction: 0.65,
        rewardSecondary: { FAIRNESS: 0.3, TRUST: 0.3, STABILITY: 0.3 },
        ownershipEffect: { taskOwner: 'reassigned_with_receipt' },
        lawEffect: { handoffRule: 'required', enforceable: true },
    },
    {
        tag: AccountabilityActionTag.AUDIT_RANDOM_SPOTCHECK,
        need: NeedTag.ACCOUNTABILITY,
        costEnergy: -0.12,
        costTime: 0.9,
        risk: 0.06, // может вызвать недовольство
        rewardSatisfaction: 0.65,
        rewardSecondary: { QUALITY: 0.3, INTEGRITY: 0.4, TRUST: 0.2 },
        requiresLocation: 'workyard|stores|gate',
        socialImpact: { TRANSPARENCY: 0.3 as any, RESENTMENT: -0.05 },
        ownershipEffect: { auditNotes: 'logged' },
    },
    {
        tag: AccountabilityActionTag.WITNESS_SIGNATURES,
        need: NeedTag.ACCOUNTABILITY,
        costEnergy: -0.06,
        costTime: 0.7,
        rewardSatisfaction: 0.6,
        rewardSecondary: { TRUST: 0.4, INTEGRITY: 0.4, FAIRNESS: 0.3 },
        tradeEffect: { wax: -1 | (0 as any) },
        socialImpact: { CREDIBILITY: 0.3, COMMUNITY: 0.2 },
        ownershipEffect: { document: 'witness_countersigned' },
    },
    {
        tag: AccountabilityActionTag.PUBLIC_RETROSPECT,
        need: NeedTag.ACCOUNTABILITY,
        costEnergy: -0.12,
        costTime: 1.2,
        rewardSatisfaction: 0.75,
        rewardSecondary: { CLARITY: 0.5, TRUST: 0.3, MORALE: 0.2 },
        requiresLocation: 'hall|yard',
        socialImpact: { COHESION: 0.3, TRANSPARENCY: 0.4 as any },
        ownershipEffect: { actionItems: 'issued_named_owners' },
    },
    {
        tag: AccountabilityActionTag.INCIDENT_REPORT_FILE,
        need: NeedTag.ACCOUNTABILITY,
        costEnergy: -0.1,
        costTime: 1.0,
        risk: 0.08, // спор о виновности
        rewardSatisfaction: 0.65,
        rewardSecondary: { SAFETY: 0.3 as any, CLARITY: 0.3, TRUST: 0.2 },
        tradeEffect: { parchment: -1, ink: -1 },
        ownershipEffect: { incidentLog: 'filed', mitigation: 'assigned' },
        lawEffect: { reportRule: 'mandatory', enforceable: true },
    },
    {
        tag: AccountabilityActionTag.CHECKLIST_BEFORE_AFTER,
        need: NeedTag.ACCOUNTABILITY,
        costEnergy: -0.08,
        costTime: 0.8,
        rewardSatisfaction: 0.65,
        rewardSecondary: { QUALITY: 0.4, EFFICIENCY: 0.2, TRUST: 0.2 },
        tradeEffect: { board_or_tablet: -1 | (0 as any) },
        ownershipEffect: { checklist: 'used_pre_post' },
    },
    {
        tag: AccountabilityActionTag.TOOL_COUNTERSIGN,
        need: NeedTag.ACCOUNTABILITY,
        costEnergy: -0.06,
        costTime: 0.7,
        rewardSatisfaction: 0.6,
        rewardSecondary: { ORDER: 0.4, TRUST: 0.3, FAIRNESS: 0.2 },
        requiresLocation: 'stores|tool_wall',
        ownershipEffect: { toolLedger: 'countersigned_in_out' },
        lawEffect: { depositRule: 'posted', enforceable: true },
    },
    {
        tag: AccountabilityActionTag.WORKLOG_STAMP,
        need: NeedTag.ACCOUNTABILITY,
        costEnergy: -0.06,
        costTime: 0.6,
        rewardSatisfaction: 0.6,
        rewardSecondary: { PRODUCTIVITY: 0.2, TRUST: 0.2, ORDER: 0.3 },
        tradeEffect: { stamp_wax: -1 | (0 as any) },
        ownershipEffect: { worklog: 'time_stamped' },
    },
    {
        tag: AccountabilityActionTag.PEER_REVIEW_ROTATION,
        need: NeedTag.ACCOUNTABILITY,
        costEnergy: -0.12,
        costTime: 1.2,
        rewardSatisfaction: 0.75,
        rewardSecondary: { QUALITY: 0.4, FAIRNESS: 0.3, TRUST: 0.3 },
        requiresLocation: 'workshop|guild_hall',
        socialImpact: { RESPECT: 0.2, COMPETITION: 0.1 },
        ownershipEffect: { reviewRoster: 'rotating_pairs' },
    },
    {
        tag: AccountabilityActionTag.ESCALATION_PATH_POST,
        need: NeedTag.ACCOUNTABILITY,
        costEnergy: -0.08,
        costTime: 0.7,
        rewardSatisfaction: 0.65,
        rewardSecondary: { CLARITY: 0.5, STABILITY: 0.3, TRUST: 0.2 },
        tradeEffect: { parchment: -1, ink: -1 },
        ownershipEffect: { noticeBoard: 'escalation_tree_posted' },
    },
    {
        tag: AccountabilityActionTag.KPI_TALLY_MARKS,
        need: NeedTag.ACCOUNTABILITY,
        costEnergy: -0.1,
        costTime: 0.9,
        rewardSatisfaction: 0.7,
        rewardSecondary: {
            PRODUCTIVITY: 0.3,
            QUALITY: 0.3,
            CONTROL: 0.3 as any,
        },
        tradeEffect: { chalk: -1, tokens: '-N' as any },
        ownershipEffect: { boardState: 'kpi_marks_visible' },
    },
    {
        tag: AccountabilityActionTag.OATH_OF_OFFICE_RENEW,
        need: NeedTag.ACCOUNTABILITY,
        costEnergy: -0.08,
        costTime: 0.8,
        rewardSatisfaction: 0.7,
        rewardSecondary: { INTEGRITY: 0.5, TRUST: 0.3, ORDER: 0.2 },
        requiresLocation: 'hall|temple',
        socialImpact: { RESPECT: 0.3, DIGNITY: 0.3 as any },
        lawEffect: { oathRecord: 'renewed', enforceable: true },
    },
    {
        tag: AccountabilityActionTag.BUDGET_POUCH_SEALS,
        need: NeedTag.ACCOUNTABILITY,
        costEnergy: -0.1,
        costTime: 0.9,
        rewardSatisfaction: 0.7,
        rewardSecondary: { TRUST: 0.4, FAIRNESS: 0.3, ORDER: 0.3 },
        tradeEffect: {
            wax: -1,
            ribbon: -1 | (0 as any),
            pouch: -1 | (0 as any),
        },
        socialImpact: { THEFT: -0.1 as any, CREDIBILITY: 0.2 },
        ownershipEffect: { treasuryPouches: 'sealed_with_countersign' },
        lawEffect: { tamperPenalty: 'severe', enforceable: true },
    },
    {
        tag: AccountabilityActionTag.FEEDBACK_ONE_ON_ONE,
        need: NeedTag.ACCOUNTABILITY,
        costEnergy: -0.1,
        costTime: 1.0,
        rewardSatisfaction: 0.75,
        rewardSecondary: { CLARITY: 0.4, QUALITY: 0.3, TRUST: 0.3 },
        requiresLocation: 'side_room|workbench',
        socialImpact: { LOYALTY: 0.2, RESENTMENT: -0.05 },
        ownershipEffect: { improvementPlan: 'agreed_named_actions' },
    },
];
