import { ActionDefinition } from '../action-definition';
import { ClarityActionTag } from '../action-tags';
import {
    cog,
    comm,
    culture,
    econ,
    fire,
    health,
    heat,
    org,
    record,
} from '../memes';
export const ClarityActions: ActionDefinition[] = [
    {
        tag: ClarityActionTag.MORNING_CLARITY_BRIEF,
        costEnergy: -0.08,
        costTime: 0.8,
        rewardSecondary: { CLARITY: 0.7, ORDER: 0.5, FOCUS: 0.4, PURPOSE: 0.3 },
        requiresLocation: 'yard|hall',
        socialImpact: { TRANSPARENCY: 0.4 as any, TRUST: 0.3 },
        ownershipEffect: { accessScope: 'notice_board', grantAccess: true },
        lawEffect: { briefRule: 'daily_required', enforceable: true },
        needRework: true,
        unclearAction: true,
        requiredMemes: [
            health.sanitation_norms,
            health.waste_handling,
            comm.language.written,
        ],
    },
    {
        tag: ClarityActionTag.TASK_DEFINITION_CARDS,
        costEnergy: -0.1,
        costTime: 1.0,
        rewardSecondary: {
            CLARITY: 0.7,
            ORDER: 0.5,
            PRODUCTIVITY: 0.3,
            FAIRNESS: 0.2,
        },
        tradeEffect: { cards: '-N' as any, ink: -1 },
        socialImpact: { ACCOUNTABILITY: 0.3 as any },
        ownershipEffect: { boardState: 'cards_with_done_criteria' },
        unclearAction: true,
        requiredMemes: [comm.language.written],
    },
    {
        tag: ClarityActionTag.ROLE_CHART_POSTING,
        costEnergy: -0.1,
        costTime: 0.9,
        rewardSecondary: {
            CLARITY: 0.65,
            ORDER: 0.5,
            TRUST: 0.3,
            INTEGRITY: 0.2,
        },
        tradeEffect: { parchment: -1, ink: -1 },
        socialImpact: { CONFLICT: -0.15 as any, RESPECT: 0.2 },
        ownershipEffect: { roleMatrix: 'posted' },
        lawEffect: { dutyCharter: 'ratified', enforceable: true },
        unclearAction: true,
        requiredMemes: [comm.language.written, org.duty_roster],
    },
    {
        tag: ClarityActionTag.SIGNAL_FLAGS_PROTOCOL,
        costEnergy: -0.08,
        costTime: 0.8,
        rewardSecondary: {
            CLARITY: 0.65,
            ORDER: 0.4,
            FOCUS: 0.3,
            STABILITY: 0.2,
        },
        tradeEffect: { flags: '-N' as any, dye: -1 | (0 as any) },
        socialImpact: { COORDINATION: 0.3 as any },
        lawEffect: { signalCode: 'posted', enforceable: true },
        ownershipEffect: { campSignals: 'active' },
    },
    {
        tag: ClarityActionTag.COMMON_GLOSSARY_CREATE,
        costEnergy: -0.14,
        costTime: 1.4,
        rewardSecondary: {
            CLARITY: 0.7,
            KNOWLEDGE: 0.4,
            INTEGRITY: 0.2,
            ORDER: 0.3,
        },
        tradeEffect: { parchment: -1, ink: -1 },
        socialImpact: { MISUNDERSTANDING: -0.3 as any, TRUST: 0.2 },
        ownershipEffect: {
            glossary: 'compiled',
            accessScope: 'library',
            grantAccess: true,
        },
        unclearAction: true,
        requiredMemes: [comm.language.written],
    },
    {
        tag: ClarityActionTag.WAYFINDING_SIGNS,
        costEnergy: -0.14,
        costTime: 1.2,
        rewardSecondary: {
            CLARITY: 0.7,
            ORDER: 0.4,
            STABILITY: 0.3,
            SECURITY: 0.2,
        },
        tradeEffect: { boards: '-N' as any, paint: -1 | (0 as any) },
        socialImpact: { LOST: -0.3 as any, FLOW: 0.2 as any },
        unclearAction: true,

        ownershipEffect: { paths: 'signed' },
    },
    {
        tag: ClarityActionTag.SHADOW_BOARD_OUTLINES,
        costEnergy: -0.12,
        costTime: 1.0,
        rewardSecondary: {
            CLARITY: 0.65,
            ORDER: 0.5,
            PRODUCTIVITY: 0.2,
            INTEGRITY: 0.2,
        },
        tradeEffect: { boards: -1 | (0 as any), paint: -1 | (0 as any) },
        socialImpact: { RESPONSIBILITY: 0.2 as any, THEFT: -0.05 as any },
        ownershipEffect: { toolWall: 'shadow_outlined' },
        unclearAction: true,

        requiredMemes: [comm.language.written],
    },
    {
        tag: ClarityActionTag.SIMPLE_LANGUAGE_TRAINING,
        costEnergy: -0.12,
        costTime: 1.2,
        rewardSecondary: {
            CLARITY: 0.7,
            FOCUS: 0.3,
            PRODUCTIVITY: 0.2,
            KNOWLEDGE: 0.3,
        },
        socialImpact: { COHESION: 0.2, RESPECT: 0.2 },
        requiredMemes: [comm.language.spoken],
    },
    {
        tag: ClarityActionTag.WRITTEN_LANGUAGE_TRAINING,
        needRework:true,
        requiredMemes: [comm.language.written],
    },
    {
        tag: ClarityActionTag.MEETING_MINUTES_RECORD,
        costEnergy: -0.1,
        costTime: 1.0,
        rewardSecondary: {
            CLARITY: 0.65,
            INTEGRITY: 0.4,
            TRUST: 0.3,
            ORDER: 0.3,
        },
        tradeEffect: { parchment: -1, ink: -1 },
        socialImpact: { TRANSPARENCY: 0.4 as any, RUMORS: -0.2 as any },
        ownershipEffect: { minutes: 'posted_summary' },
        lawEffect: { minutesRule: 'required', enforceable: true },
        unclearAction: true,
        needRework: true,
        requiredMemes: [comm.language.written, record.ledgerkeeping],
    },
    {
        tag: ClarityActionTag.LEDGER_SUMMARY_WEEK,
        costEnergy: -0.12,
        costTime: 1.2,
        rewardSecondary: {
            CLARITY: 0.7,
            TRUST: 0.4,
            ORDER: 0.3,
            FAIRNESS: 0.2,
        },
        requiresLocation: 'clerk_desk|hall',
        socialImpact: { TRANSPARENCY: 0.4 as any },
        ownershipEffect: { summaryScroll: 'posted' },
        unclearAction: true,
        requiredMemes: [comm.language.written, record.ledgerkeeping],
    },
    {
        tag: ClarityActionTag.QUESTIONS_OPEN_HOUR,
        costEnergy: -0.08,
        costTime: 0.9,
        rewardSecondary: {
            CLARITY: 0.7,
            TRUST: 0.3,
            COMMUNITY: 0.2,
            PURPOSE: 0.2,
        },
        requiresLocation: 'hall|square',
        socialImpact: { RESENTMENT: -0.1, COHESION: 0.2 },
        lawEffect: { audienceRight: 'announced', enforceable: true },
        unclearAction: true,
        needRework: true,
    },
    {
        tag: ClarityActionTag.RUMOR_DEBUNK_BULLETIN,
        costEnergy: -0.08,
        costTime: 0.8,
        risk: 0.08,
        rewardSecondary: {
            CLARITY: 0.65,
            TRUST: 0.3,
            ORDER: 0.3,
            STABILITY: 0.3,
        },
        tradeEffect: { parchment: -1, ink: -1 },
        socialImpact: { RUMORS: -0.4 as any, CREDIBILITY: 0.3 },
        ownershipEffect: { noticeBoard: 'debunk_posted' },
        unclearAction: true,
        requiredMemes: [comm.language.written],
    },
    {
        tag: ClarityActionTag.VISUAL_WORK_INSTRUCTIONS,
        costEnergy: -0.16,
        costTime: 1.4,
        rewardSecondary: {
            CLARITY: 0.75,
            PRODUCTIVITY: 0.3,
            QUALITY: 0.3,
            FOCUS: 0.3,
        },
        requiresLocation: 'workbench|forge|loom',
        tradeEffect: { boards: -1 | (0 as any), paint: -1 | (0 as any) },
        socialImpact: { TRAINING: 0.3 as any },
        ownershipEffect: { poster: 'mounted' },
        needRework: true,
    },
    {
        tag: ClarityActionTag.PROGRESS_MARK_TOTEM,
        costEnergy: -0.1,
        costTime: 1.0,
        rewardSecondary: {
            CLARITY: 0.7,
            PURPOSE: 0.3,
            MORALE: 0.3,
            ORDER: 0.2,
        },
        requiresLocation: 'yard|worksite',
        tradeEffect: {
            stakes: '-N' as any,
            rope: -1 | (0 as any),
            dye: -1 | (0 as any),
        },
        socialImpact: { MOTIVATION: 0.3 as any, PANIC: -0.1 as any },
        ownershipEffect: { milestone: 'visible_scale' },
        needRework: true,
    },
    {
        tag: ClarityActionTag.NIGHTLY_STATUS_RUNDOWN,
        costEnergy: -0.08,
        costTime: 0.9,
        rewardSecondary: {
            CLARITY: 0.7,
            ORDER: 0.4,
            STABILITY: 0.3,
            TRUST: 0.3,
        },
        requiresLocation: 'hall|hearth',
        socialImpact: { COHESION: 0.2, ACCOUNTABILITY: 0.2 as any },
        ownershipEffect: { logbook: 'end_of_day_update' },
        unclearAction: true,
        requiredMemes: [
            culture.vigil_ritual,
            cog.timekeeping.basic,
            heat.space.hearth,
            comm.language.written,
        ],
    },
    {
        tag: ClarityActionTag.MAP_AND_TERRAIN_BRIEF,
        costEnergy: -0.12,
        costTime: 1.0,
        rewardSecondary: {
            CLARITY: 0.75,
            SECURITY: 0.3,
            PURPOSE: 0.3,
            READINESS: 0.3 as any,
        },
        requiresLocation: 'war_room|hall|camp',
        tradeEffect: { parchment: -1, ink: -1, tokens: '-N' as any },
        socialImpact: { TRUST: 0.2, COURAGE: 0.2 },
        ownershipEffect: { mapState: 'annotated' },
        unclearAction: true,
        requiredMemes: [
            comm.language.written,
            record.ledgerkeeping,
            econ.pooling_common_fund,
        ],
    },
];
