import { ActionDefinition } from '../action-definition';
import { ClarityActionTag } from '../action-tags';
import { NeedTag } from '../needs';

export const ClarityActions: ActionDefinition[] = [
    {
        tag: ClarityActionTag.MORNING_CLARITY_BRIEF,
        need: NeedTag.CLARITY,
        costEnergy: -0.08,
        costTime: 0.8,
        rewardSatisfaction: 0.7,
        rewardSecondary: { ORDER: 0.5, FOCUS: 0.4, PURPOSE: 0.3 },
        requiresLocation: 'yard|hall',
        socialImpact: { TRANSPARENCY: 0.4 as any, TRUST: 0.3 },
        ownershipEffect: { accessScope: 'notice_board', grantAccess: true },
        lawEffect: { briefRule: 'daily_required', enforceable: true },
    },
    {
        tag: ClarityActionTag.TASK_DEFINITION_CARDS,
        need: NeedTag.CLARITY,
        costEnergy: -0.1,
        costTime: 1.0,
        rewardSatisfaction: 0.7,
        rewardSecondary: { ORDER: 0.5, PRODUCTIVITY: 0.3, FAIRNESS: 0.2 },
        tradeEffect: { cards: '-N' as any, ink: -1 },
        socialImpact: { ACCOUNTABILITY: 0.3 as any },
        ownershipEffect: { boardState: 'cards_with_done_criteria' },
    },
    {
        tag: ClarityActionTag.ROLE_CHART_POSTING,
        need: NeedTag.CLARITY,
        costEnergy: -0.1,
        costTime: 0.9,
        rewardSatisfaction: 0.65,
        rewardSecondary: { ORDER: 0.5, TRUST: 0.3, INTEGRITY: 0.2 },
        tradeEffect: { parchment: -1, ink: -1 },
        socialImpact: { CONFLICT: -0.15 as any, RESPECT: 0.2 },
        ownershipEffect: { roleMatrix: 'posted' },
        lawEffect: { dutyCharter: 'ratified', enforceable: true },
    },
    {
        tag: ClarityActionTag.SIGNAL_FLAGS_PROTOCOL,
        need: NeedTag.CLARITY,
        costEnergy: -0.08,
        costTime: 0.8,
        rewardSatisfaction: 0.65,
        rewardSecondary: { ORDER: 0.4, FOCUS: 0.3, STABILITY: 0.2 },
        tradeEffect: { flags: '-N' as any, dye: -1 | (0 as any) },
        socialImpact: { COORDINATION: 0.3 as any },
        lawEffect: { signalCode: 'posted', enforceable: true },
        ownershipEffect: { campSignals: 'active' },
    },
    {
        tag: ClarityActionTag.COMMON_GLOSSARY_CREATE,
        need: NeedTag.CLARITY,
        costEnergy: -0.14,
        costTime: 1.4,
        rewardSatisfaction: 0.7,
        rewardSecondary: { KNOWLEDGE: 0.4, INTEGRITY: 0.2, ORDER: 0.3 },
        tradeEffect: { parchment: -1, ink: -1 },
        socialImpact: { MISUNDERSTANDING: -0.3 as any, TRUST: 0.2 },
        ownershipEffect: {
            glossary: 'compiled',
            accessScope: 'library',
            grantAccess: true,
        },
    },
    {
        tag: ClarityActionTag.WAYFINDING_SIGNS,
        need: NeedTag.CLARITY,
        costEnergy: -0.14,
        costTime: 1.2,
        rewardSatisfaction: 0.7,
        rewardSecondary: { ORDER: 0.4, STABILITY: 0.3, SECURITY: 0.2 },
        tradeEffect: { boards: '-N' as any, paint: -1 | (0 as any) },
        socialImpact: { LOST: -0.3 as any, FLOW: 0.2 as any },
        ownershipEffect: { paths: 'signed' },
    },
    {
        tag: ClarityActionTag.SHADOW_BOARD_OUTLINES,
        need: NeedTag.CLARITY,
        costEnergy: -0.12,
        costTime: 1.0,
        rewardSatisfaction: 0.65,
        rewardSecondary: { ORDER: 0.5, PRODUCTIVITY: 0.2, INTEGRITY: 0.2 },
        tradeEffect: { boards: -1 | (0 as any), paint: -1 | (0 as any) },
        socialImpact: { RESPONSIBILITY: 0.2 as any, THEFT: -0.05 as any },
        ownershipEffect: { toolWall: 'shadow_outlined' },
    },
    {
        tag: ClarityActionTag.SIMPLE_LANGUAGE_TRAINING,
        need: NeedTag.CLARITY,
        costEnergy: -0.12,
        costTime: 1.2,
        rewardSatisfaction: 0.7,
        rewardSecondary: { FOCUS: 0.3, PRODUCTIVITY: 0.2, KNOWLEDGE: 0.3 },
        requiresLocation: 'hall|workshop',
        socialImpact: { COHESION: 0.2, RESPECT: 0.2 },
        ownershipEffect: { primer: 'issued' },
    },
    {
        tag: ClarityActionTag.MEETING_MINUTES_RECORD,
        need: NeedTag.CLARITY,
        costEnergy: -0.1,
        costTime: 1.0,
        rewardSatisfaction: 0.65,
        rewardSecondary: { INTEGRITY: 0.4, TRUST: 0.3, ORDER: 0.3 },
        tradeEffect: { parchment: -1, ink: -1 },
        socialImpact: { TRANSPARENCY: 0.4 as any, RUMORS: -0.2 as any },
        ownershipEffect: { minutes: 'posted_summary' },
        lawEffect: { minutesRule: 'required', enforceable: true },
    },
    {
        tag: ClarityActionTag.LEDGER_SUMMARY_WEEK,
        need: NeedTag.CLARITY,
        costEnergy: -0.12,
        costTime: 1.2,
        rewardSatisfaction: 0.7,
        rewardSecondary: { TRUST: 0.4, ORDER: 0.3, FAIRNESS: 0.2 },
        requiresLocation: 'clerk_desk|hall',
        socialImpact: { TRANSPARENCY: 0.4 as any },
        ownershipEffect: { summaryScroll: 'posted' },
    },
    {
        tag: ClarityActionTag.QUESTIONS_OPEN_HOUR,
        need: NeedTag.CLARITY,
        costEnergy: -0.08,
        costTime: 0.9,
        rewardSatisfaction: 0.7,
        rewardSecondary: { TRUST: 0.3, COMMUNITY: 0.2, PURPOSE: 0.2 },
        requiresLocation: 'hall|square',
        socialImpact: { RESENTMENT: -0.1, COHESION: 0.2 },
        lawEffect: { audienceRight: 'announced', enforceable: true },
    },
    {
        tag: ClarityActionTag.RUMOR_DEBUNK_BULLETIN,
        need: NeedTag.CLARITY,
        costEnergy: -0.08,
        costTime: 0.8,
        risk: 0.08, // затронут чью-то гордость
        rewardSatisfaction: 0.65,
        rewardSecondary: { TRUST: 0.3, ORDER: 0.3, STABILITY: 0.3 },
        tradeEffect: { parchment: -1, ink: -1 },
        socialImpact: { RUMORS: -0.4 as any, CREDIBILITY: 0.3 },
        ownershipEffect: { noticeBoard: 'debunk_posted' },
    },
    {
        tag: ClarityActionTag.VISUAL_WORK_INSTRUCTIONS,
        need: NeedTag.CLARITY,
        costEnergy: -0.16,
        costTime: 1.4,
        rewardSatisfaction: 0.75,
        rewardSecondary: { PRODUCTIVITY: 0.3, QUALITY: 0.3, FOCUS: 0.3 },
        requiresLocation: 'workbench|forge|loom',
        tradeEffect: { boards: -1 | (0 as any), paint: -1 | (0 as any) },
        socialImpact: { TRAINING: 0.3 as any },
        ownershipEffect: { poster: 'mounted' },
    },
    {
        tag: ClarityActionTag.PROGRESS_MARK_TOTEM,
        need: NeedTag.CLARITY,
        costEnergy: -0.1,
        costTime: 1.0,
        rewardSatisfaction: 0.7,
        rewardSecondary: { PURPOSE: 0.3, MORALE: 0.3, ORDER: 0.2 },
        requiresLocation: 'yard|worksite',
        tradeEffect: {
            stakes: '-N' as any,
            rope: -1 | (0 as any),
            dye: -1 | (0 as any),
        },
        socialImpact: { MOTIVATION: 0.3 as any, PANIC: -0.1 as any },
        ownershipEffect: { milestone: 'visible_scale' },
    },
    {
        tag: ClarityActionTag.NIGHTLY_STATUS_RUNDOWN,
        need: NeedTag.CLARITY,
        costEnergy: -0.08,
        costTime: 0.9,
        rewardSatisfaction: 0.7,
        rewardSecondary: { ORDER: 0.4, STABILITY: 0.3, TRUST: 0.3 },
        requiresLocation: 'hall|hearth',
        socialImpact: { COHESION: 0.2, ACCOUNTABILITY: 0.2 as any },
        ownershipEffect: { logbook: 'end_of_day_update' },
    },
    {
        tag: ClarityActionTag.MAP_AND_TERRAIN_BRIEF,
        need: NeedTag.CLARITY,
        costEnergy: -0.12,
        costTime: 1.0,
        rewardSatisfaction: 0.75,
        rewardSecondary: { SECURITY: 0.3, PURPOSE: 0.3, READINESS: 0.3 as any },
        requiresLocation: 'war_room|hall|camp',
        tradeEffect: { parchment: -1, ink: -1, tokens: '-N' as any },
        socialImpact: { TRUST: 0.2, COURAGE: 0.2 },
        ownershipEffect: { mapState: 'annotated' },
    },
];
