import { ActionDefinition } from '../action-definition';
import { CultureActionTag } from '../action-tags';
import { NeedTag } from '../needs';

export const CultureActions: ActionDefinition[] = [
    {
        tag: CultureActionTag.FESTIVAL_ORGANIZE,
        need: NeedTag.CULTURE,
        costEnergy: -0.28,
        costTime: 2.6,
        risk: 0.14, // нехватка припасов/погодный фактор
        rewardSatisfaction: 0.95,
        rewardSecondary: {
            COMMUNITY: 0.6,
            JOY: 0.6 as any,
            MORALE: 0.5,
            STATUS: 0.3,
        },
        requiresLocation: 'square|hall|fields',
        tradeEffect: {
            food: '-N' as any,
            drink: '-N' as any,
            garlands: '-N' as any,
        },
        socialImpact: { NETWORK: 0.3, RESPECT: 0.2 },
        lawEffect: { gatheringPermit: 'approved', enforceable: true },
        ownershipEffect: { accessScope: 'stalls|stage', grantAccess: true },
    },
    {
        tag: CultureActionTag.ORAL_HISTORY_CIRCLE,
        need: NeedTag.CULTURE,
        costEnergy: -0.12,
        costTime: 1.4,
        rewardSatisfaction: 0.75,
        rewardSecondary: { IDENTITY: 0.5, TRADITION: 0.5, KNOWLEDGE: 0.3 },
        requiresLocation: 'hall|hearth',
        socialImpact: { COMMUNITY: 0.4, RESPECT: 0.2 },
        ownershipEffect: { loreLog: 'updated' },
    },
    {
        tag: CultureActionTag.CRAFT_GUILD_EXHIBIT,
        need: NeedTag.CULTURE,
        costEnergy: -0.2,
        costTime: 2.0,
        rewardSatisfaction: 0.85,
        rewardSecondary: { STATUS: 0.4, NETWORK: 0.4, REPUTATION: 0.3 },
        requiresLocation: 'guild_hall|market',
        tradeEffect: { booth_fee: -1 as any, decorations: -1 },
        socialImpact: { COMMUNITY: 0.3, RESPECT: 0.3 },
        lawEffect: { exhibitEtiquette: 'observed', enforceable: true },
    },
    {
        tag: CultureActionTag.RITES_OF_PASSAGE,
        need: NeedTag.CULTURE,
        costEnergy: -0.18,
        costTime: 1.8,
        risk: 0.1,
        rewardSatisfaction: 0.9,
        rewardSecondary: { IDENTITY: 0.6, HONOR: 0.4, TRADITION: 0.5 },
        requiresLocation: 'temple|sacred_grove',
        socialImpact: { RESPECT: 0.4, COMMUNITY: 0.3 },
        lawEffect: { riteRegister: 'recorded', enforceable: true },
        ownershipEffect: { token: 'granted', rights: 'adult_privileges' },
    },
    {
        tag: CultureActionTag.SEASONAL_DECORATIONS,
        need: NeedTag.CULTURE,
        costEnergy: -0.14,
        costTime: 1.2,
        rewardSatisfaction: 0.75,
        rewardSecondary: { JOY: 0.5 as any, COMMUNITY: 0.3, TRADITION: 0.4 },
        tradeEffect: {
            ribbons: '-N' as any,
            dye: -1 | (0 as any),
            candles: -1 | (0 as any),
        },
        socialImpact: { AESTHETIC: 0.3 as any, COHESION: 0.2 },
        ownershipEffect: { districtLook: 'festive' },
    },
    {
        tag: CultureActionTag.SONG_DANCE_REHEARSAL,
        need: NeedTag.CULTURE,
        costEnergy: -0.16,
        costTime: 1.6,
        rewardSatisfaction: 0.8,
        rewardSecondary: { COMMUNITY: 0.4, MORALE: 0.4, JOY: 0.4 as any },
        requiresLocation: 'hall|green',
        socialImpact: { COHESION: 0.4, NETWORK: 0.2 },
        ownershipEffect: { repertoire: 'expanded' },
    },
    {
        tag: CultureActionTag.STORYTELLER_NIGHT,
        need: NeedTag.CULTURE,
        costEnergy: -0.12,
        costTime: 1.4,
        rewardSatisfaction: 0.8,
        rewardSecondary: { KNOWLEDGE: 0.4, IDENTITY: 0.3, JOY: 0.3 as any },
        requiresLocation: 'hearth|hall',
        tradeEffect: { small_fee: -1 | (0 as any) },
        socialImpact: { RESPECT: 0.2, COMMUNITY: 0.3 },
        ownershipEffect: { anthology: 'added_tale' },
    },
    {
        tag: CultureActionTag.HERITAGE_MARKERS,
        need: NeedTag.CULTURE,
        costEnergy: -0.2,
        costTime: 1.8,
        rewardSatisfaction: 0.8,
        rewardSecondary: { IDENTITY: 0.5, RESPECT: 0.3, TRADITION: 0.4 },
        tradeEffect: { stone: '-N' as any, chisel_wear: '-minor' },
        socialImpact: { MEMORY: 0.4 as any, COMMUNITY: 0.3 },
        lawEffect: { heritageRegistry: 'updated', enforceable: true },
        ownershipEffect: { siteStatus: 'protected' },
    },
    {
        tag: CultureActionTag.SHARED_MEAL_FEAST,
        need: NeedTag.CULTURE,
        costEnergy: -0.24,
        costTime: 2.2,
        rewardSatisfaction: 0.95,
        rewardSecondary: { COMMUNITY: 0.6, JOY: 0.6 as any, TRUST: 0.3 },
        requiresLocation: 'hall|square|barn',
        tradeEffect: {
            grain: '-N' as any,
            meat: '-N' as any,
            ale: '-N' as any,
        },
        socialImpact: { BELONGING: 0.5 as any, NETWORK: 0.2 },
        ownershipEffect: { storesLevel: 'reduced_feast' },
    },
    {
        tag: CultureActionTag.ARTISAN_CONTEST,
        need: NeedTag.CULTURE,
        costEnergy: -0.2,
        costTime: 2.0,
        rewardSatisfaction: 0.85,
        rewardSecondary: { STATUS: 0.4, REPUTATION: 0.3, INNOVATION_REP: 0.3 },
        requiresLocation: 'guild_hall|market',
        tradeEffect: { prize_fund: -1 as any, ribbons: '-N' as any },
        socialImpact: { COMPETITION: 0.3, RESPECT: 0.3 },
        lawEffect: { contestRules: 'posted', enforceable: true },
        ownershipEffect: { laurels: 'awarded' },
    },
    {
        tag: CultureActionTag.SYMBOLS_STANDARDIZE,
        need: NeedTag.CULTURE,
        costEnergy: -0.14,
        costTime: 1.4,
        rewardSatisfaction: 0.7,
        rewardSecondary: { CLARITY: 0.5, IDENTITY: 0.5, ORDER: 0.3 },
        tradeEffect: { dye: -1 | (0 as any), seals: '-N' as any },
        socialImpact: { UNITY: 0.3 as any, RESPECT: 0.2 },
        lawEffect: { heraldryRoll: 'ratified', enforceable: true },
        ownershipEffect: { banners: 'standardized' },
    },
    {
        tag: CultureActionTag.CULTURAL_EXCHANGE_FAIR,
        need: NeedTag.CULTURE,
        costEnergy: -0.24,
        costTime: 2.2,
        risk: 0.12, // культурные трения
        rewardSatisfaction: 0.9,
        rewardSecondary: { NETWORK: 0.5, KNOWLEDGE: 0.4, COMMUNITY: 0.3 },
        requiresLocation: 'market|square',
        tradeEffect: { booths: '-N' as any, gifts: '-N' as any },
        socialImpact: { TOLERANCE: 0.4 as any, RESPECT: 0.2 },
        lawEffect: { guestRight: 'declared', enforceable: true },
    },
    {
        tag: CultureActionTag.TEACH_CHILDREN_CUSTOMS,
        need: NeedTag.CULTURE,
        costEnergy: -0.16,
        costTime: 1.6,
        rewardSatisfaction: 0.8,
        rewardSecondary: { TRADITION: 0.6, IDENTITY: 0.5, COMMUNITY: 0.3 },
        requiresLocation: 'school|hearth|temple',
        socialImpact: { RESPECT: 0.2, HOPE: 0.3 as any },
        ownershipEffect: { primer: 'compiled' },
    },
    {
        tag: CultureActionTag.MEMORIAL_SERVICE,
        need: NeedTag.CULTURE,
        costEnergy: -0.18,
        costTime: 1.6,
        rewardSatisfaction: 0.85,
        rewardSecondary: { RESILIENCE: 0.4, COMMUNITY: 0.3, HONOR: 0.3 },
        requiresLocation: 'temple|graveyard',
        socialImpact: { DIGNITY: 0.4 as any, COHESION: 0.3 },
        lawEffect: { processionPermit: 'granted', enforceable: true },
    },
    {
        tag: CultureActionTag.PATRONAGE_CHARTER,
        need: NeedTag.CULTURE,
        costEnergy: -0.2,
        costTime: 1.8,
        rewardSatisfaction: 0.85,
        rewardSecondary: { STATUS: 0.4, TRUST: 0.3, WEALTH: 0.2 },
        tradeEffect: { endowment: -1 as any },
        socialImpact: { NETWORK: 0.3, RESPECT: 0.3 },
        lawEffect: { patronCharter: 'sealed', enforceable: true },
        ownershipEffect: { workshopGrants: 'enabled' },
    },
    {
        tag: CultureActionTag.ARCHIVE_SONGS_AND_PATTERNS,
        need: NeedTag.CULTURE,
        costEnergy: -0.16,
        costTime: 1.6,
        rewardSatisfaction: 0.75,
        rewardSecondary: { KNOWLEDGE: 0.5, IDENTITY: 0.3, ORDER: 0.3 },
        requiresItem: ['parchment|wax_tablet', 'ink|stylus'],
        socialImpact: { RESPECT: 0.2, HERITAGE: 0.3 as any },
        ownershipEffect: {
            archiveState: 'indexed',
            accessScope: 'library',
            grantAccess: true,
        },
        lawEffect: { archivePolicy: 'preservation', enforceable: true },
    },
];
