import { ActionDefinition } from '../action-definition';
import { EnergyActionTag } from '../action-tags';
import { NeedTag } from '../needs';

export const EnergyActions: ActionDefinition[] = [
    {
        tag: EnergyActionTag.HIGH_PROTEIN_MEAL,
        need: NeedTag.ENERGY,
        costEnergy: +0.35,
        costTime: 1.0,
        rewardSatisfaction: 0.85,
        rewardSecondary: { HEALTH: 0.4, PRODUCTIVITY: 0.2, RESILIENCE: 0.2 },
        requiresLocation: 'mess|hall|hearth',
        tradeEffect: {
            meat_or_legumes: '-N' as any,
            bread: '-1 | 0' as any,
            herbs: '-1 | 0' as any,
        },
        ownershipEffect: { storesLevel: 'reduced_meal' },
    },
    {
        tag: EnergyActionTag.POWER_NAP_20,
        need: NeedTag.ENERGY,
        costEnergy: +0.25,
        costTime: 0.5,
        rewardSatisfaction: 0.75,
        rewardSecondary: { HEALTH: 0.2, FOCUS: 0.2, RESILIENCE: 0.2 },
        requiresLocation: 'bunks|hearth',
        ownershipEffect: { berthUse: 'short_rest' },
    },
    {
        tag: EnergyActionTag.SUNLIGHT_STRETCH,
        need: NeedTag.ENERGY,
        costEnergy: +0.12,
        costTime: 0.5,
        rewardSatisfaction: 0.65,
        rewardSecondary: { HEALTH: 0.2, JOY: 0.2 as any, FOCUS: 0.15 },
        requiresLocation: 'yard|green|balcony',
        socialImpact: { CALM: 0.2 as any },
    },
    {
        tag: EnergyActionTag.SHORT_SPRINT_EXERCISE,
        need: NeedTag.ENERGY,
        costEnergy: -0.08, // расход сейчас → бодрость позже
        costTime: 0.4,
        rewardSatisfaction: 0.6,
        rewardSecondary: { HEALTH: 0.2, READINESS: 0.2 as any, MORALE: 0.15 },
        requiresLocation: 'yard|track|field',
        risk: 0.04, // перетрен
    },
    {
        tag: EnergyActionTag.CAFFEINE_HERB_TONIC,
        need: NeedTag.ENERGY,
        costEnergy: +0.18,
        costTime: 0.4,
        rewardSatisfaction: 0.7,
        rewardSecondary: { FOCUS: 0.3, PRODUCTIVITY: 0.2, MORALE: 0.15 },
        tradeEffect: { tonic_herbs_or_coffee: -1, honey: -1 | (0 as any) },
        risk: 0.05, // дрожь/откат
        ownershipEffect: { kettleState: 'brewed' },
    },
    {
        tag: EnergyActionTag.BREATH_OXY_DRILL,
        need: NeedTag.ENERGY,
        costEnergy: +0.1,
        costTime: 0.3,
        rewardSatisfaction: 0.6,
        rewardSecondary: { FOCUS: 0.2, RESILIENCE: 0.2, CLARITY: 0.2 },
        requiresLocation: 'quiet_corner|hearth',
    },
    {
        tag: EnergyActionTag.WATER_REHYDRATE,
        need: NeedTag.ENERGY,
        costEnergy: +0.15,
        costTime: 0.2,
        rewardSatisfaction: 0.55,
        rewardSecondary: { HEALTH: 0.25, STABILITY: 0.15, FOCUS: 0.1 },
        requiresLocation: 'well|canteen',
        tradeEffect: {
            clean_water: -1,
            salt_or_ash_electrolyte: -1 | (0 as any),
        },
        ownershipEffect: { canteen: 'refilled' },
    },
    {
        tag: EnergyActionTag.MICRO_BREAK_EYESTRAIN,
        need: NeedTag.ENERGY,
        costEnergy: +0.06,
        costTime: 0.2,
        rewardSatisfaction: 0.5,
        rewardSecondary: { PRODUCTIVITY: 0.15, FOCUS: 0.2, HEALTH: 0.1 },
        ownershipEffect: { taskState: 'paused_micro' },
    },
    {
        tag: EnergyActionTag.POSTURE_RESET,
        need: NeedTag.ENERGY,
        costEnergy: +0.08,
        costTime: 0.25,
        rewardSatisfaction: 0.55,
        rewardSecondary: { HEALTH: 0.2, FOCUS: 0.15, PRODUCTIVITY: 0.1 },
        requiresLocation: 'workroom|yard',
        socialImpact: { DIGNITY: 0.1 as any },
    },
    {
        tag: EnergyActionTag.SNACK_TRAIL_MIX,
        need: NeedTag.ENERGY,
        costEnergy: +0.18,
        costTime: 0.3,
        rewardSatisfaction: 0.65,
        rewardSecondary: { HEALTH: 0.15, PRODUCTIVITY: 0.15, JOY: 0.1 as any },
        tradeEffect: {
            nuts: -1 | (0 as any),
            dried_fruit: -1 | (0 as any),
            grain_bar: -1 | (0 as any),
        },
        ownershipEffect: { storesLevel: 'reduced_snacks' },
    },
    {
        tag: EnergyActionTag.SOCIAL_ENERGY_CHECKIN,
        need: NeedTag.ENERGY,
        costEnergy: +0.1,
        costTime: 0.5,
        rewardSatisfaction: 0.65,
        rewardSecondary: { MORALE: 0.3, COMMUNITY: 0.2, RESILIENCE: 0.2 },
        requiresLocation: 'hearth|hall|workyard',
        socialImpact: { COHESION: 0.2, STRESS: -0.1 as any },
    },
    {
        tag: EnergyActionTag.WORKLOAD_REBALANCE,
        need: NeedTag.ENERGY,
        costEnergy: +0.08, // снимает перегруз
        costTime: 0.8,
        rewardSatisfaction: 0.7,
        rewardSecondary: { STABILITY: 0.3, PRODUCTIVITY: 0.2, FAIRNESS: 0.2 },
        requiresSkill: 'leadership|planning',
        socialImpact: { RESENTMENT: -0.1, TRUST: 0.2 },
        ownershipEffect: { dutyRoster: 'rebalanced' },
        lawEffect: { fatigueLimits: 'posted', enforceable: true },
    },
    {
        tag: EnergyActionTag.EARLY_LIGHTS_OUT,
        need: NeedTag.ENERGY,
        costEnergy: +0.4,
        costTime: 1.6,
        rewardSatisfaction: 0.85,
        rewardSecondary: {
            HEALTH: 0.3,
            RESILIENCE: 0.3,
            READINESS: 0.2 as any,
        },
        requiresLocation: 'bunks|home',
        lawEffect: { quietHours: 'observed', enforceable: true },
        ownershipEffect: { curfewReady: 'true' },
    },
    {
        tag: EnergyActionTag.MORNING_COLD_SPLASH,
        need: NeedTag.ENERGY,
        costEnergy: +0.12,
        costTime: 0.3,
        rewardSatisfaction: 0.6,
        rewardSecondary: { READINESS: 0.2 as any, COURAGE: 0.1, HEALTH: 0.1 },
        requiresLocation: 'well|river',
        risk: 0.03, // простуда в плохую погоду
    },
    {
        tag: EnergyActionTag.WARMUP_BEFORE_LABOR,
        need: NeedTag.ENERGY,
        costEnergy: -0.04, // лёгкий расход → меньше травм
        costTime: 0.4,
        rewardSatisfaction: 0.6,
        rewardSecondary: {
            READINESS: 0.3 as any,
            HEALTH: 0.2,
            PRODUCTIVITY: 0.15,
        },
        requiresLocation: 'yard|worksite',
        socialImpact: { SAFETY: 0.2 as any },
    },
    {
        tag: EnergyActionTag.RECOVERY_MASSAGE,
        need: NeedTag.ENERGY,
        costEnergy: +0.22,
        costTime: 1.0,
        rewardSatisfaction: 0.8,
        rewardSecondary: { HEALTH: 0.3, RESILIENCE: 0.3, MORALE: 0.2 },
        requiresLocation: 'baths|hearth',
        requiresSkill: 'massage|healer_craft',
        tradeEffect: { oil: -1 | (0 as any), herbs: -1 | (0 as any) },
        socialImpact: { CARE: 0.3 as any },
    },
];
