import { ActionDefinition } from '../action-definition';
import { IntegrityActionTag } from '../action-tags';
import { NeedTag } from '../needs';

export const IntegrityActions: ActionDefinition[] = [
    {
        tag: IntegrityActionTag.TELL_TRUTH_UNDER_OATH,
        need: NeedTag.INTEGRITY,
        costEnergy: -0.12,
        costTime: 1.0,
        risk: 0.15, // последствия правды для связей
        rewardSatisfaction: 0.8,
        rewardSecondary: { JUSTICE: 0.6, TRUST: 0.5, CLARITY: 0.4 },
        requiresLocation: 'hall|court_square|temple',
        socialImpact: { CREDIBILITY: 0.5, RESPECT: 0.3 },
        lawEffect: { oathRecord: 'sworn_truthful', enforceable: true },
    },
    {
        tag: IntegrityActionTag.REFUSE_PLAGIARISM,
        need: NeedTag.INTEGRITY,
        costEnergy: -0.06,
        costTime: 0.6,
        rewardSatisfaction: 0.65,
        rewardSecondary: { REPUTATION: 0.3, FAIRNESS: 0.3, CULTURE: 0.2 },
        socialImpact: { RESPECT: 0.2, CORRUPTION: -0.2 as any },
        lawEffect: { authorshipRule: 'observed', enforceable: true },
    },
    {
        tag: IntegrityActionTag.RETURN_OVERPAYMENT,
        need: NeedTag.INTEGRITY,
        costEnergy: -0.06,
        costTime: 0.6,
        rewardSatisfaction: 0.7,
        rewardSecondary: { TRUST: 0.4, HONOR: 0.3, ORDER: 0.2 },
        tradeEffect: { coin: '-refund' },
        socialImpact: { COMMUNITY: 0.2, GRATITUDE: 0.3 as any },
        lawEffect: { ledgerCorrection: 'filed', enforceable: true },
    },
    {
        tag: IntegrityActionTag.CORRECT_RECORDS_ERROR,
        need: NeedTag.INTEGRITY,
        costEnergy: -0.1,
        costTime: 0.9,
        rewardSatisfaction: 0.7,
        rewardSecondary: { CLARITY: 0.6, ORDER: 0.4, STABILITY: 0.3 },
        tradeEffect: { ink: -1 | (0 as any) },
        socialImpact: { TRANSPARENCY: 0.3 as any, TRUST: 0.2 },
        ownershipEffect: { ledgerState: 'amended' },
        lawEffect: { erratumNote: 'attached', enforceable: true },
    },
    {
        tag: IntegrityActionTag.REPORT_CONFLICT_OF_INTEREST,
        need: NeedTag.INTEGRITY,
        costEnergy: -0.08,
        costTime: 0.8,
        risk: 0.08,
        rewardSatisfaction: 0.75,
        rewardSecondary: { CLARITY: 0.5, JUSTICE: 0.4, TRUST: 0.3 },
        socialImpact: { CORRUPTION: -0.3 as any, RESPECT: 0.2 },
        lawEffect: { conflictRegistry: 'declared', enforceable: true },
    },
    {
        tag: IntegrityActionTag.DECLARE_GIFTS_HOSPITALITY,
        need: NeedTag.INTEGRITY,
        costEnergy: -0.08,
        costTime: 0.8,
        rewardSatisfaction: 0.65,
        rewardSecondary: { CLARITY: 0.5, TRUST: 0.3, ORDER: 0.2 },
        tradeEffect: { gift_value: 'declared' },
        socialImpact: { TRANSPARENCY: 0.3 as any, CORRUPTION: -0.2 as any },
        lawEffect: { giftLedger: 'updated', enforceable: true },
    },
    {
        tag: IntegrityActionTag.KEEP_CONFIDENTIALITY,
        need: NeedTag.INTEGRITY,
        costEnergy: -0.04,
        costTime: 0.5,
        rewardSatisfaction: 0.55,
        rewardSecondary: { TRUST: 0.4, PRIVACY: 0.4, STABILITY: 0.2 },
        socialImpact: { RELIABILITY: 0.3 as any },
        lawEffect: { privacyRule: 'respected', enforceable: true },
    },
    {
        tag: IntegrityActionTag.REFUSE_FALSE_TESTIMONY,
        need: NeedTag.INTEGRITY,
        costEnergy: -0.1,
        costTime: 0.8,
        risk: 0.12,
        rewardSatisfaction: 0.8,
        rewardSecondary: { JUSTICE: 0.5, COURAGE: 0.3, TRUST: 0.3 },
        requiresLocation: 'hall|court_square',
        socialImpact: { CREDIBILITY: 0.4, FEAR: -0.05 },
        lawEffect: { perjuryAttempt: 'refused', enforceable: true },
    },
    {
        tag: IntegrityActionTag.HONOR_BOUNDARY_CONSENT,
        need: NeedTag.INTEGRITY,
        costEnergy: -0.05,
        costTime: 0.6,
        rewardSatisfaction: 0.6,
        rewardSecondary: { RESPECT: 0.3, TRUST: 0.3, COMMUNITY: 0.2 },
        socialImpact: { DIGNITY: 0.4 as any, HARM: -0.2 as any },
        lawEffect: { consentRule: 'affirmed', enforceable: true },
    },
    {
        tag: IntegrityActionTag.FAIR_WEIGHTS_MAINTAIN,
        need: NeedTag.INTEGRITY,
        costEnergy: -0.12,
        costTime: 1.0,
        rewardSatisfaction: 0.65,
        rewardSecondary: { FAIRNESS: 0.5, TRUST: 0.4, WEALTH: 0.1 },
        tradeEffect: { calibration_weights: -1 | (0 as any) },
        socialImpact: { REPUTATION: 0.2, DISPUTES: -0.1 as any },
        lawEffect: { measureSeal: 'stamped', enforceable: true },
    },
    {
        tag: IntegrityActionTag.AVOID_NEPOTISM_IN_ASSIGNMENT,
        need: NeedTag.INTEGRITY,
        costEnergy: -0.1,
        costTime: 0.9,
        risk: 0.08,
        rewardSatisfaction: 0.7,
        rewardSecondary: { FAIRNESS: 0.5, TRUST: 0.3, ORDER: 0.3 },
        socialImpact: { RESENTMENT: -0.2, ACCEPTANCE: 0.2 as any },
        lawEffect: { assignmentRule: 'merit_first', enforceable: true },
    },
    {
        tag: IntegrityActionTag.PROPER_ATTRIBUTION,
        need: NeedTag.INTEGRITY,
        costEnergy: -0.06,
        costTime: 0.7,
        rewardSatisfaction: 0.7,
        rewardSecondary: { RESPECT: 0.3, REPUTATION: 0.3, COMMUNITY: 0.2 },
        ownershipEffect: { record: 'co_authorship', rights: 'shared' },
        socialImpact: { TRUST: 0.3, RESENTMENT: -0.1 },
        lawEffect: { creditNote: 'filed', enforceable: true },
    },
    {
        tag: IntegrityActionTag.AUDIT_PERSONAL_ACCOUNTS,
        need: NeedTag.INTEGRITY,
        costEnergy: -0.14,
        costTime: 1.2,
        risk: 0.06,
        rewardSatisfaction: 0.7,
        rewardSecondary: { CLARITY: 0.6, STABILITY: 0.3, TRUST: 0.3 },
        requiresItem: ['abacus|tally_sticks'],
        socialImpact: { TRANSPARENCY: 0.4 as any },
        ownershipEffect: { purseLedger: 'balanced' },
        lawEffect: { auditRoll: 'filed', enforceable: true },
    },
    {
        tag: IntegrityActionTag.RECUSE_FROM_DECISION,
        need: NeedTag.INTEGRITY,
        costEnergy: -0.08,
        costTime: 0.8,
        rewardSatisfaction: 0.75,
        rewardSecondary: { JUSTICE: 0.5, TRUST: 0.4, ORDER: 0.3 },
        socialImpact: { RESPECT: 0.3, CORRUPTION: -0.3 as any },
        lawEffect: { recusalNote: 'posted', enforceable: true },
    },
    {
        tag: IntegrityActionTag.ETHICAL_SOURCING,
        need: NeedTag.INTEGRITY,
        costEnergy: -0.16,
        costTime: 1.6,
        risk: 0.08, // сырьё может подорожать
        rewardSatisfaction: 0.75,
        rewardSecondary: {
            JUSTICE: 0.4,
            TRUST: 0.3,
            CULTURE: 0.2,
            STABILITY: 0.2,
        },
        tradeEffect: { supplier_blacklist: 'updated' },
        socialImpact: { REPUTATION: 0.3, COMMUNITY: 0.2 },
        lawEffect: { sourcingCharter: 'ratified', enforceable: true },
    },
    {
        tag: IntegrityActionTag.CODE_OF_CONDUCT_REFRESH,
        need: NeedTag.INTEGRITY,
        costEnergy: -0.12,
        costTime: 1.2,
        rewardSatisfaction: 0.7,
        rewardSecondary: { CLARITY: 0.5, DISCIPLINE: 0.4, ORDER: 0.3 },
        requiresLocation: 'hall|workshop',
        tradeEffect: { parchment: -1, ink: -1 },
        socialImpact: { TRUST: 0.2, COHESION: 0.2 },
        ownershipEffect: { accessScope: 'training_room', grantAccess: true },
        lawEffect: { codeCharter: 'reaffirmed', enforceable: true },
    },
];
