import { ActionDefinition } from '../action-definition';
import { JoyActionTag } from '../action-tags';
import { NeedTag } from '../needs';

export const JoyActions: ActionDefinition[] = [
    {
        tag: JoyActionTag.PLAY_MUSIC_TOGETHER,
        need: NeedTag.JOY,
        costEnergy: -0.08,
        costTime: 0.8,
        rewardSatisfaction: 0.85,
        rewardSecondary: { MORALE: 0.5, COMMUNITY: 0.4, CULTURE: 0.3 },
        requiresLocation: 'hearth|hall|green',
        requiresItem: ['flute|drum|lyre'],
        socialImpact: { COHESION: 0.3, RHYTHM: 0.2 as any },
    },
    {
        tag: JoyActionTag.DANCE_RING,
        need: NeedTag.JOY,
        costEnergy: -0.14,
        costTime: 1.0,
        risk: 0.04, // неловкость/усталость
        rewardSatisfaction: 0.9,
        rewardSecondary: { MORALE: 0.6, COMMUNITY: 0.4, HEALTH: 0.2 },
        requiresLocation: 'square|green|hall',
        socialImpact: { COHESION: 0.4, STATUS: 0.1 },
        ownershipEffect: { floorSpace: 'cleared' },
    },
    {
        tag: JoyActionTag.JOKE_STORY_SWAP,
        need: NeedTag.JOY,
        costEnergy: -0.04,
        costTime: 0.6,
        rewardSatisfaction: 0.75,
        rewardSecondary: {
            SOCIAL: 0.4 as any,
            COMMUNITY: 0.3,
            RESILIENCE: 0.2,
        },
        requiresLocation: 'hearth|mess',
        socialImpact: { EMPATHY: 0.3 as any, RUMORS: -0.1 as any },
    },
    {
        tag: JoyActionTag.SWEET_TREAT_SHARE,
        need: NeedTag.JOY,
        costEnergy: -0.06,
        costTime: 0.6,
        rewardSatisfaction: 0.8,
        rewardSecondary: { LOVE: 0.3, COMMUNITY: 0.3, HEALTH: 0.1 },
        tradeEffect: { honey_cakes: '-N' as any, berries: '-N' as any },
        socialImpact: { GRATITUDE: 0.4 as any, TRUST: 0.2 },
        ownershipEffect: { storesLevel: 'reduced_treat' },
    },
    {
        tag: JoyActionTag.PICNIC_OUTING,
        need: NeedTag.JOY,
        costEnergy: -0.12,
        costTime: 1.2,
        risk: 0.06, // погода/насекомые
        rewardSatisfaction: 0.85,
        rewardSecondary: { HEALTH: 0.3, COMMUNITY: 0.3, MORALE: 0.3 },
        requiresLocation: 'meadow|river_bank|grove',
        tradeEffect: { bread: -1, fruit: -1 | (0 as any) },
        socialImpact: { COHESION: 0.3, STRESS: -0.2 as any },
    },
    {
        tag: JoyActionTag.FIREWORK_SPARK_SHOW,
        need: NeedTag.JOY,
        costEnergy: -0.1,
        costTime: 0.8,
        risk: 0.08, // ожоги/пожар
        rewardSatisfaction: 0.9,
        rewardSecondary: { CULTURE: 0.3, COMMUNITY: 0.3, MORALE: 0.4 },
        requiresLocation: 'square|river_bank',
        tradeEffect: { pitch: -1 | (0 as any), powder: -1 | (0 as any) },
        socialImpact: { AWE: 0.5 as any, PANIC: -0.05 as any },
        lawEffect: { fireSafety: 'strict', enforceable: true },
    },
    {
        tag: JoyActionTag.CHILDREN_GAMES_HOST,
        need: NeedTag.JOY,
        costEnergy: -0.1,
        costTime: 1.0,
        rewardSatisfaction: 0.85,
        rewardSecondary: { COMMUNITY: 0.4, LOVE: 0.3, MORALE: 0.3 },
        requiresLocation: 'green|yard',
        socialImpact: { FAMILY: 0.4 as any, HOPE: 0.3 as any },
        ownershipEffect: { playArea: 'chalk_marked' },
    },
    {
        tag: JoyActionTag.HOBBY_CRAFT_HOUR,
        need: NeedTag.JOY,
        costEnergy: -0.12,
        costTime: 1.2,
        rewardSatisfaction: 0.8,
        rewardSecondary: { CULTURE: 0.3, PRODUCTIVITY: 0.2, IDENTITY: 0.2 },
        requiresLocation: 'workbench|loom|carving_table',
        tradeEffect: {
            wood: '-N' as any,
            yarn: '-N' as any,
            dye: -1 | (0 as any),
        },
        socialImpact: { CREATIVITY: 0.4 as any },
        ownershipEffect: { trinkets: '+N' },
    },
    {
        tag: JoyActionTag.PRAISE_WITH_LAUGHTER,
        need: NeedTag.JOY,
        costEnergy: -0.04,
        costTime: 0.5,
        rewardSatisfaction: 0.75,
        rewardSecondary: { MORALE: 0.4, SOCIAL: 0.3 as any, RESPECT: 0.2 },
        requiresLocation: 'hall|yard',
        socialImpact: { COHESION: 0.3, RESENTMENT: -0.05 },
        ownershipEffect: { honorRoll: 'fun_titles_added' },
    },
    {
        tag: JoyActionTag.SURPRISE_GIFT_TOKEN,
        need: NeedTag.JOY,
        costEnergy: -0.06,
        costTime: 0.6,
        rewardSatisfaction: 0.85,
        rewardSecondary: { LOVE: 0.4, COMMUNITY: 0.2, TRUST: 0.2 },
        tradeEffect: { token: -1, ribbon: -1 | (0 as any) },
        socialImpact: { GRATITUDE: 0.5 as any, BOND: 0.3 as any },
        ownershipEffect: { recipientGift: '+1' },
    },
    {
        tag: JoyActionTag.COMMUNITY_THEATRE,
        need: NeedTag.JOY,
        costEnergy: -0.2,
        costTime: 1.8,
        rewardSatisfaction: 0.9,
        rewardSecondary: { CULTURE: 0.5, COMMUNITY: 0.4, MORALE: 0.4 },
        requiresLocation: 'hall|square',
        tradeEffect: { props: '-N' as any, dye: -1 | (0 as any) },
        socialImpact: { COHESION: 0.4, REPUTATION: 0.2 },
        ownershipEffect: { stageState: 'set' },
    },
    {
        tag: JoyActionTag.FISHING_PLEASURE_TRIP,
        need: NeedTag.JOY,
        costEnergy: -0.12,
        costTime: 1.4,
        risk: 0.06,
        rewardSatisfaction: 0.8,
        rewardSecondary: { HEALTH: 0.2, RESILIENCE: 0.2, COMMUNITY: 0.2 },
        requiresLocation: 'river|lake',
        requiresItem: ['rod|net|hooks'],
        socialImpact: { CALM: 0.3 as any, NETWORK: 0.1 },
        ownershipEffect: { catch: '+small' },
    },
    {
        tag: JoyActionTag.DRESS_UP_FEST_ATTIRE,
        need: NeedTag.JOY,
        costEnergy: -0.08,
        costTime: 0.8,
        rewardSatisfaction: 0.8,
        rewardSecondary: { CULTURE: 0.4, STATUS: 0.2, COMMUNITY: 0.2 },
        tradeEffect: { ribbons: '-N' as any, polish: -1 | (0 as any) },
        socialImpact: { VISIBILITY: 0.3 as any, RESPECT: 0.1 },
        ownershipEffect: { attireState: 'festive' },
    },
    {
        tag: JoyActionTag.GARDEN_BLOSSOM_WALK,
        need: NeedTag.JOY,
        costEnergy: -0.06,
        costTime: 0.7,
        rewardSatisfaction: 0.75,
        rewardSecondary: { HEALTH: 0.2, RESILIENCE: 0.2, COMMUNITY: 0.1 },
        requiresLocation: 'garden|orchard|grove',
        socialImpact: { CALM: 0.3 as any },
        ownershipEffect: { pathUse: 'stroll' },
    },
    {
        tag: JoyActionTag.FRIENDSHIP_TOAST,
        need: NeedTag.JOY,
        costEnergy: -0.06,
        costTime: 0.6,
        risk: 0.04, // перебор с выпивкой
        rewardSatisfaction: 0.85,
        rewardSecondary: { COMMUNITY: 0.4, LOVE: 0.3, MORALE: 0.3 },
        requiresLocation: 'mess|hearth|square',
        tradeEffect: { ale_or_kvass: -1 | (0 as any) },
        socialImpact: { BOND: 0.4 as any, TRUST: 0.2 },
    },
    {
        tag: JoyActionTag.FUN_COMPETITION_FAIR,
        need: NeedTag.JOY,
        costEnergy: -0.14,
        costTime: 1.2,
        risk: 0.06, // споры о победителях
        rewardSatisfaction: 0.9,
        rewardSecondary: { COMMUNITY: 0.4, MORALE: 0.4, CULTURE: 0.2 },
        requiresLocation: 'green|yard|square',
        tradeEffect: { ribbons: '-N' as any, prize_token: -1 | (0 as any) },
        socialImpact: { COHESION: 0.4, COMPETITION: 0.2 },
        ownershipEffect: { fieldState: 'game_lines' },
    },
];
