import { ActionDefinition } from '../action-definition';
import { MoraleActionTag } from '../action-tags';
import { NeedTag } from '../needs';

export const MoraleActions: ActionDefinition[] = [
    {
        tag: MoraleActionTag.RALLY_SPEECH,
        need: NeedTag.MORALE,
        costEnergy: -0.08,
        costTime: 0.8,
        risk: 0.08, // может не «зайти»
        rewardSatisfaction: 0.75,
        rewardSecondary: { COURAGE: 0.4, TRUST: 0.3, CLARITY: 0.2 },
        requiresLocation: 'yard|hall|square',
        socialImpact: { COHESION: 0.3 as any, RESPECT: 0.2 },
        lawEffect: { speechRule: 'no_defamation', enforceable: true },
    },
    {
        tag: MoraleActionTag.CELEBRATE_SMALL_WIN,
        need: NeedTag.MORALE,
        costEnergy: -0.1,
        costTime: 1.0,
        rewardSatisfaction: 0.85,
        rewardSecondary: { JOY: 0.6 as any, COMMUNITY: 0.4, STABILITY: 0.2 },
        tradeEffect: { bread: -1, ale: '-1 | 0' as any },
        socialImpact: { BELONGING: 0.3 as any, NETWORK: 0.2 },
        ownershipEffect: { memoryLog: 'win_marked' },
    },
    {
        tag: MoraleActionTag.ISSUE_COMMENDATION_TOKEN,
        need: NeedTag.MORALE,
        costEnergy: -0.06,
        costTime: 0.7,
        rewardSatisfaction: 0.8,
        rewardSecondary: { STATUS: 0.4, RESPECT: 0.3, TRUST: 0.2 },
        tradeEffect: { ribbon_or_token: -1 },
        socialImpact: { FAIRNESS: 0.2, COMPETITION: 0.2 },
        ownershipEffect: { accolade: 'awarded', rights: 'display' },
        lawEffect: { honorRoll: 'updated', enforceable: true },
    },
    {
        tag: MoraleActionTag.BANNER_RAISING,
        need: NeedTag.MORALE,
        costEnergy: -0.08,
        costTime: 0.8,
        rewardSatisfaction: 0.7,
        rewardSecondary: { IDENTITY: 0.5, CULTURE: 0.3, COURAGE: 0.2 },
        requiresLocation: 'gate|square|camp_mast',
        tradeEffect: { banner: '-wear', rope: '-1 | 0' as any },
        socialImpact: { UNITY: 0.3 as any, VISIBILITY: 0.3 as any },
        ownershipEffect: { campState: 'banner_flies' },
    },
    {
        tag: MoraleActionTag.SHARED_SONG_AT_WORK,
        need: NeedTag.MORALE,
        costEnergy: -0.04,
        costTime: 0.6,
        rewardSatisfaction: 0.7,
        rewardSecondary: {
            JOY: 0.4 as any,
            COMMUNITY: 0.3,
            PRODUCTIVITY: 0.15,
        },
        requiresLocation: 'workyard|road|fields',
        socialImpact: { COHESION: 0.3 as any, RHYTHM: 0.2 as any },
    },
    {
        tag: MoraleActionTag.REST_DAY_ROTATION,
        need: NeedTag.MORALE,
        costEnergy: -0.02,
        costTime: 0.3,
        rewardSatisfaction: 0.65,
        rewardSecondary: { STABILITY: 0.4, FAIRNESS: 0.3, HEALTH: 0.2 },
        socialImpact: { TRUST: 0.2, RESENTMENT: -0.1 },
        lawEffect: { rota: 'rest_day_posted', enforceable: true },
        ownershipEffect: { accessScope: 'common_amenities', grantAccess: true },
    },
    {
        tag: MoraleActionTag.WARM_MEAL_DISTRIBUTION,
        need: NeedTag.MORALE,
        costEnergy: -0.14,
        costTime: 1.0,
        rewardSatisfaction: 0.85,
        rewardSecondary: { JOY: 0.5 as any, HEALTH: 0.2, COMMUNITY: 0.3 },
        requiresLocation: 'mess|hall|camp_kitchen',
        tradeEffect: { stew: '-N' as any, bread: '-N' as any },
        socialImpact: { GRATITUDE: 0.4 as any, TRUST: 0.2 },
        ownershipEffect: { storesLevel: 'reduced_meal' },
    },
    {
        tag: MoraleActionTag.FIRE_HEARTH_GATHER,
        need: NeedTag.MORALE,
        costEnergy: -0.1,
        costTime: 1.0,
        rewardSatisfaction: 0.8,
        rewardSecondary: { COMMUNITY: 0.4, RESILIENCE: 0.3, JOY: 0.3 as any },
        requiresLocation: 'hearth|campfire',
        tradeEffect: { firewood: -1, lamp_oil: -1 | (0 as any) },
        socialImpact: { STORYTELLING: 0.3 as any, COHESION: 0.3 },
        lawEffect: { fireSafety: 'observed', enforceable: true },
    },
    {
        tag: MoraleActionTag.TEAM_GAME_SPORT,
        need: NeedTag.MORALE,
        costEnergy: -0.16,
        costTime: 1.2,
        risk: 0.06, // травмы/споры
        rewardSatisfaction: 0.9,
        rewardSecondary: { JOY: 0.6 as any, COMMUNITY: 0.4, TRUST: 0.2 },
        requiresLocation: 'green|yard',
        socialImpact: { COHESION: 0.4, STATUS: 0.2 },
        ownershipEffect: { fieldState: 'lines_marked' },
    },
    {
        tag: MoraleActionTag.LETTERS_FROM_HOME_READING,
        need: NeedTag.MORALE,
        costEnergy: -0.06,
        costTime: 0.8,
        risk: 0.04, // могут быть плохие вести
        rewardSatisfaction: 0.7,
        rewardSecondary: { IDENTITY: 0.3, COMMUNITY: 0.2, RESILIENCE: 0.2 },
        requiresLocation: 'mess|hearth|chapel',
        socialImpact: { PRIVACY: 0.2 as any, EMPATHY: 0.3 as any },
        ownershipEffect: { letter: 'read|archived' },
    },
    {
        tag: MoraleActionTag.HONOR_FALLEN_RITES,
        need: NeedTag.MORALE,
        costEnergy: -0.18,
        costTime: 1.4,
        rewardSatisfaction: 0.85,
        rewardSecondary: { RESILIENCE: 0.5, COMMUNITY: 0.4, HONOR: 0.3 },
        requiresLocation: 'temple|graveyard|memorial',
        socialImpact: { DIGNITY: 0.4 as any, COHESION: 0.3 },
        lawEffect: { processionPermit: 'granted', enforceable: true },
        ownershipEffect: { memorialRoll: 'updated' },
    },
    {
        tag: MoraleActionTag.SUCCESS_TALLY_BOARD,
        need: NeedTag.MORALE,
        costEnergy: -0.06,
        costTime: 0.6,
        rewardSatisfaction: 0.7,
        rewardSecondary: { CLARITY: 0.4, TRUST: 0.3, STATUS: 0.2 },
        tradeEffect: { chalk: -1, board_use: '+1' },
        socialImpact: { TRANSPARENCY: 0.3 as any, MOTIVATION: 0.3 as any },
        ownershipEffect: { boardState: 'wins_posted' },
    },
    {
        tag: MoraleActionTag.PAIR_NEW_WITH_VETERAN,
        need: NeedTag.MORALE,
        costEnergy: -0.12,
        costTime: 1.0,
        rewardSatisfaction: 0.75,
        rewardSecondary: { TRUST: 0.4, RESILIENCE: 0.3, COMMUNITY: 0.3 },
        requiresSkill: 'mentoring|apprentice',
        socialImpact: { LOYALTY: 0.3, COHESION: 0.3 },
        ownershipEffect: { accessScope: 'mentor_area', grantAccess: true },
        lawEffect: { pairingRoster: 'logged', enforceable: true },
    },
    {
        tag: MoraleActionTag.HOPE_STORIES_SHARING,
        need: NeedTag.MORALE,
        costEnergy: -0.08,
        costTime: 0.9,
        rewardSatisfaction: 0.75,
        rewardSecondary: { RESILIENCE: 0.4, COMMUNITY: 0.3, JOY: 0.3 as any },
        requiresLocation: 'hearth|hall',
        socialImpact: { EMPATHY: 0.4 as any, COHESION: 0.3 },
    },
    {
        tag: MoraleActionTag.CLEAN_AND_DECORATE_COMMONS,
        need: NeedTag.MORALE,
        costEnergy: -0.16,
        costTime: 1.4,
        rewardSatisfaction: 0.8,
        rewardSecondary: { JOY: 0.4 as any, COMMUNITY: 0.3, ORDER: 0.3 },
        tradeEffect: {
            garlands: '-N' as any,
            rags: '-wear',
            dye: -1 | (0 as any),
        },
        socialImpact: { DIGNITY: 0.3 as any, BELONGING: 0.3 as any },
        ownershipEffect: { commonsState: 'bright_and_clean' },
    },
    {
        tag: MoraleActionTag.SET_SYMBOLIC_GOAL_MARKER,
        need: NeedTag.MORALE,
        costEnergy: -0.08,
        costTime: 0.8,
        rewardSatisfaction: 0.7,
        rewardSecondary: { CLARITY: 0.4, PURPOSE: 0.3, COMMUNITY: 0.2 },
        tradeEffect: { banner: -1 | (0 as any), stakes: '-N' as any },
        socialImpact: { MOTIVATION: 0.4 as any, UNITY: 0.2 as any },
        ownershipEffect: { milestone: 'planted', progress: 'trackable' },
    },
];
