import { ActionDefinition } from '../action-definition';
import { NetworkActionTag } from '../action-tags';
import { NeedTag } from '../needs';

export const NetworkActions: ActionDefinition[] = [
    {
        tag: NetworkActionTag.MARKET_MEET_AND_GREET,
        need: NeedTag.NETWORK,
        costEnergy: -0.08,
        costTime: 0.9,
        rewardSatisfaction: 0.65,
        rewardSecondary: { COMMUNITY: 0.4, TRUST: 0.3, REPUTATION: 0.2 },
        requiresLocation: 'market|fair',
        socialImpact: { INTRODUCTIONS: 0.5 as any, VISIBILITY: 0.2 as any },
        ownershipEffect: { contactList: '+N' },
    },
    {
        tag: NetworkActionTag.LETTER_OF_INTRODUCTION,
        need: NeedTag.NETWORK,
        costEnergy: -0.06,
        costTime: 0.7,
        rewardSatisfaction: 0.6,
        rewardSecondary: { TRUST: 0.4, CLARITY: 0.3, REPUTATION: 0.2 },
        tradeEffect: { parchment: -1, ink: -1, wax: '-1 | 0' as any },
        socialImpact: { CREDIBILITY: 0.3, ACCESS: 0.3 as any },
        ownershipEffect: { letterState: 'sealed', chainOfCustody: 'tracked' },
        lawEffect: { sealRight: 'recognized', enforceable: true },
    },
    {
        tag: NetworkActionTag.HOST_GUEST_MERCHANT,
        need: NeedTag.NETWORK,
        costEnergy: -0.12,
        costTime: 1.2,
        risk: 0.08, // риск споров/ущерба
        rewardSatisfaction: 0.75,
        rewardSecondary: { COMMUNITY: 0.4, TRUST: 0.3, WEALTH: 0.2 },
        requiresLocation: 'guest_house|hearth',
        tradeEffect: { meal: -1, bedding: '-1 | 0' as any },
        socialImpact: { HOSPITALITY: 0.5 as any, RESPECT: 0.2 },
        ownershipEffect: { guestBook: 'signed' },
        lawEffect: { guestRight: 'declared', enforceable: true },
    },
    {
        tag: NetworkActionTag.RECIPROCAL_FAVORS_LEDGER,
        need: NeedTag.NETWORK,
        costEnergy: -0.08,
        costTime: 0.9,
        rewardSatisfaction: 0.7,
        rewardSecondary: { FAIRNESS: 0.3, TRUST: 0.3, STABILITY: 0.2 },
        tradeEffect: { parchment: -1, ink: -1 },
        socialImpact: { ACCOUNTABILITY: 0.3 as any, RESENTMENT: -0.05 },
        ownershipEffect: { favorsLedger: 'opened' },
        lawEffect: { reciprocityRule: 'posted', enforceable: true },
    },
    {
        tag: NetworkActionTag.GUILD_GREETING_RITUAL,
        need: NeedTag.NETWORK,
        costEnergy: -0.06,
        costTime: 0.6,
        rewardSatisfaction: 0.6,
        rewardSecondary: { COMMUNITY: 0.4, CULTURE: 0.2, REPUTATION: 0.2 },
        requiresLocation: 'guild_hall|workshop',
        socialImpact: { BELONGING: 0.4 as any, STATUS: 0.2 },
        lawEffect: { guildEtiquette: 'observed', enforceable: true },
    },
    {
        tag: NetworkActionTag.SHARED_TOOLS_LIBRARY,
        need: NeedTag.NETWORK,
        costEnergy: -0.14,
        costTime: 1.2,
        rewardSatisfaction: 0.75,
        rewardSecondary: { TRUST: 0.3, WEALTH: 0.2, PRODUCTIVITY: 0.2 },
        requiresLocation: 'stores|workyard',
        socialImpact: { COOPERATION: 0.4 as any, LOSS: -0.05 as any },
        ownershipEffect: { accessScope: 'members_tools', grantAccess: true },
        lawEffect: { depositRule: 'posted', enforceable: true },
    },
    {
        tag: NetworkActionTag.ESCORT_CARAVAN,
        need: NeedTag.NETWORK,
        costEnergy: -0.18,
        costTime: 1.6,
        risk: 0.16,
        rewardSatisfaction: 0.8,
        rewardSecondary: { TRUST: 0.4, REPUTATION: 0.3, WEALTH: 0.2 },
        requiresLocation: 'road|pass|bridge',
        socialImpact: { RELIABILITY: 0.4 as any, COMMUNITY: 0.2 },
        ownershipEffect: { escortRecord: 'filed' },
        lawEffect: { caravanPact: 'sealed', enforceable: true },
    },
    {
        tag: NetworkActionTag.COUNCIL_OF_NEIGHBORS,
        need: NeedTag.NETWORK,
        costEnergy: -0.14,
        costTime: 1.4,
        rewardSatisfaction: 0.8,
        rewardSecondary: { COMMUNITY: 0.5, STABILITY: 0.4, CLARITY: 0.3 },
        requiresLocation: 'hall|neutral_meadow',
        socialImpact: { COHESION: 0.4, RESPECT: 0.2 },
        ownershipEffect: { treaties: 'minutes_posted' },
        lawEffect: { mootRight: 'recognized', enforceable: true },
    },
    {
        tag: NetworkActionTag.HOST_CRAFT_SALON,
        need: NeedTag.NETWORK,
        costEnergy: -0.12,
        costTime: 1.2,
        rewardSatisfaction: 0.75,
        rewardSecondary: { KNOWLEDGE: 0.4, REPUTATION: 0.3, COMMUNITY: 0.3 },
        requiresLocation: 'hall|workshop',
        socialImpact: { INTRODUCTIONS: 0.4 as any, STATUS: 0.2 },
        ownershipEffect: { guestList: '+N' },
    },
    {
        tag: NetworkActionTag.PATRON_SPONSORSHIP,
        need: NeedTag.NETWORK,
        costEnergy: -0.1,
        costTime: 1.0,
        risk: 0.08, // провал подопечного бьёт по репутации
        rewardSatisfaction: 0.8,
        rewardSecondary: { STATUS: 0.4, TRUST: 0.3, REPUTATION: 0.3 },
        socialImpact: { LOYALTY: 0.4, COMMUNITY: 0.3 },
        ownershipEffect: { letterOfMark: 'issued' },
        lawEffect: { sponsorshipRoll: 'filed', enforceable: true },
    },
    {
        tag: NetworkActionTag.NOTICE_BOARD_INTROS,
        need: NeedTag.NETWORK,
        costEnergy: -0.06,
        costTime: 0.6,
        rewardSatisfaction: 0.65,
        rewardSecondary: { CLARITY: 0.3, COMMUNITY: 0.2, WEALTH: 0.2 },
        requiresLocation: 'square|hall',
        tradeEffect: { parchment: -1, ink: -1 },
        socialImpact: { MATCHING: 0.4 as any, RUMORS: -0.05 as any },
        ownershipEffect: { noticeBoard: 'intros_posted' },
    },
    {
        tag: NetworkActionTag.FESTIVAL_OF_ALLIANCES,
        need: NeedTag.NETWORK,
        costEnergy: -0.24,
        costTime: 2.2,
        rewardSatisfaction: 0.9,
        rewardSecondary: { COMMUNITY: 0.6, TRUST: 0.4, CULTURE: 0.3 },
        requiresLocation: 'square|hall|fields',
        tradeEffect: {
            food: '-N' as any,
            drink: '-N' as any,
            ribbons: '-N' as any,
        },
        socialImpact: { COHESION: 0.5, RESPECT: 0.3 },
        ownershipEffect: { alliances: '+ties' },
        lawEffect: { guestRight: 'declared', enforceable: true },
    },
    {
        tag: NetworkActionTag.MESSENGER_EXCHANGE,
        need: NeedTag.NETWORK,
        costEnergy: -0.12,
        costTime: 1.0,
        rewardSatisfaction: 0.75,
        rewardSecondary: { TRUST: 0.4, STABILITY: 0.3, CLARITY: 0.3 },
        tradeEffect: { retainers: -1 as any, feed: '-1 | 0' as any },
        socialImpact: { RELIABILITY: 0.4 as any, VISIBILITY: 0.2 as any },
        ownershipEffect: { courierLine: 'established' },
        lawEffect: { sealRight: 'recognized', enforceable: true },
    },
    {
        tag: NetworkActionTag.SKILL_BARTER_DAY,
        need: NeedTag.NETWORK,
        costEnergy: -0.14,
        costTime: 1.4,
        rewardSatisfaction: 0.8,
        rewardSecondary: { KNOWLEDGE: 0.5, COMMUNITY: 0.4, REPUTATION: 0.2 },
        requiresLocation: 'guild_hall|yard',
        socialImpact: { MENTORING: 0.4 as any, ACCESS: 0.2 as any },
        ownershipEffect: { roster: 'mentors_and_slots' },
    },
    {
        tag: NetworkActionTag.MUTUAL_DEFENSE_PLEDGE,
        need: NeedTag.NETWORK,
        costEnergy: -0.12,
        costTime: 1.0,
        risk: 0.12, // обязательства по тревоге
        rewardSatisfaction: 0.8,
        rewardSecondary: { TRUST: 0.5, STABILITY: 0.4, COURAGE: 0.2 },
        requiresLocation: 'hall|sacred_grove',
        socialImpact: { LOYALTY: 0.4, COMMUNITY: 0.3 },
        lawEffect: { hornRight: 'mutual_aid_sworn', enforceable: true },
        ownershipEffect: { musterProtocol: 'shared' },
    },
    {
        tag: NetworkActionTag.TRADE_ROUTE_MAPPING,
        need: NeedTag.NETWORK,
        costEnergy: -0.12,
        costTime: 1.0,
        rewardSatisfaction: 0.75,
        rewardSecondary: { CLARITY: 0.5, WEALTH: 0.3, STABILITY: 0.3 },
        tradeEffect: { parchment: -1, ink: -1, markers: '-N' as any },
        socialImpact: { OPPORTUNITY: 0.4 as any, CONFLICT: -0.05 as any },
        ownershipEffect: { routeMap: 'hubs_marked', contactList: '+merchants' },
    },
];
