import { ActionDefinition } from '../action-definition';
import { PrivacyActionTag } from '../action-tags';
import { NeedTag } from '../needs';

export const PrivacyActions: ActionDefinition[] = [
    {
        tag: PrivacyActionTag.CREATE_PRIVATE_QUARTERS,
        need: NeedTag.PRIVACY,
        costEnergy: -0.18,
        costTime: 1.8,
        rewardSatisfaction: 0.85,
        rewardSecondary: { STABILITY: 0.4, SECURITY: 0.3, CONTROL: 0.3 as any },
        requiresLocation: 'house|longhouse|barracks',
        tradeEffect: {
            curtains: -1,
            chest: -1 | (0 as any),
            rugs: -1 | (0 as any),
        },
        socialImpact: { RESPECT: 0.2, CONFLICT: -0.05 as any },
        ownershipEffect: {
            roomState: 'private_quarters',
            accessScope: 'owner_only',
        },
        lawEffect: { trespassRule: 'posted', enforceable: true },
    },
    {
        tag: PrivacyActionTag.SET_SCREEN_PARTITIONS,
        need: NeedTag.PRIVACY,
        costEnergy: -0.14,
        costTime: 1.2,
        rewardSatisfaction: 0.7,
        rewardSecondary: { CONTROL: 0.3 as any, STABILITY: 0.3, CLARITY: 0.2 },
        tradeEffect: {
            screens: -1,
            rope: -1 | (0 as any),
            stakes: '-N' as any,
        },
        socialImpact: { BOUNDARIES: 0.3 as any },
        ownershipEffect: { areaDivision: 'partitioned' },
    },
    {
        tag: PrivacyActionTag.SECURE_STORAGE_CHEST,
        need: NeedTag.PRIVACY,
        costEnergy: -0.12,
        costTime: 1.0,
        rewardSatisfaction: 0.7,
        rewardSecondary: { SECURITY: 0.4, TRUST: 0.2, STABILITY: 0.2 },
        tradeEffect: { chest: -1 | (0 as any), lock_or_seal: -1 | (0 as any) },
        socialImpact: { THEFT: -0.1 as any, RESPECT: 0.1 },
        ownershipEffect: {
            chestState: 'locked|sealed',
            accessScope: 'owner_only',
        },
        lawEffect: { sealTamperPenalty: 'fine|shame', enforceable: true },
    },
    {
        tag: PrivacyActionTag.QUIET_ZONE_DECLARATION,
        need: NeedTag.PRIVACY,
        costEnergy: -0.06,
        costTime: 0.6,
        rewardSatisfaction: 0.6,
        rewardSecondary: { CLARITY: 0.3, STABILITY: 0.3, TRUST: 0.2 },
        requiresLocation: 'hall|library|hearth',
        socialImpact: { CALM: 0.3 as any, RESPECT: 0.2 },
        lawEffect: { quietHours: 'posted', enforceable: true },
        ownershipEffect: { accessScope: 'quiet_zone', grantAccess: true },
    },
    {
        tag: PrivacyActionTag.PRIVATE_COUNSEL_MEET,
        need: NeedTag.PRIVACY,
        costEnergy: -0.08,
        costTime: 0.9,
        rewardSatisfaction: 0.7,
        rewardSecondary: { TRUST: 0.4, INTEGRITY: 0.3, CLARITY: 0.2 },
        requiresLocation: 'side_room|sacristy|study',
        socialImpact: { GOSSIP: -0.1 as any },
        lawEffect: { confidentialityRule: 'affirmed', enforceable: true },
    },
    {
        tag: PrivacyActionTag.REDACT_SENSITIVE_RECORDS,
        need: NeedTag.PRIVACY,
        costEnergy: -0.1,
        costTime: 1.0,
        rewardSatisfaction: 0.65,
        rewardSecondary: { INTEGRITY: 0.4, TRUST: 0.3, ORDER: 0.2 },
        tradeEffect: { ink: -1, wax: -1 | (0 as any) },
        socialImpact: { TRANSPARENCY: 0.2 as any, HARM: -0.1 as any },
        ownershipEffect: {
            ledgerState: 'redacted',
            accessScope: 'need_to_know',
        },
        lawEffect: { privacyRoll: 'updated', enforceable: true },
    },
    {
        tag: PrivacyActionTag.CONFIDE_TRUSTED_CONFIDANT,
        need: NeedTag.PRIVACY,
        costEnergy: -0.06,
        costTime: 0.8,
        risk: 0.06, // может «проболтаться»
        rewardSatisfaction: 0.7,
        rewardSecondary: { TRUST: 0.4, RESILIENCE: 0.2, CLARITY: 0.2 },
        requiresSkill: 'empathy|counsel',
        socialImpact: { BOND: 0.3 as any, GOSSIP: -0.05 as any },
        lawEffect: { oathOfSilence: 'sworn', enforceable: false },
    },
    {
        tag: PrivacyActionTag.PERSONAL_TIME_BLOCK,
        need: NeedTag.PRIVACY,
        costEnergy: -0.04,
        costTime: 0.5,
        rewardSatisfaction: 0.6,
        rewardSecondary: { STABILITY: 0.3, CONTROL: 0.3 as any, FOCUS: 0.2 },
        socialImpact: { RESPECT: 0.2, CONFLICT: -0.05 as any },
        lawEffect: { doNotDisturb: 'posted', enforceable: true },
    },
    {
        tag: PrivacyActionTag.MARKET_PRIVACY_CURTAIN,
        need: NeedTag.PRIVACY,
        costEnergy: -0.08,
        costTime: 0.8,
        rewardSatisfaction: 0.65,
        rewardSecondary: { TRUST: 0.3, SECURITY: 0.2, FAIRNESS: 0.2 },
        requiresLocation: 'market|stall',
        tradeEffect: { curtain: -1, hooks: -1 | (0 as any) },
        socialImpact: { GOSSIP: -0.1 as any, CREDIBILITY: 0.1 },
        ownershipEffect: { boothState: 'curtained' },
        lawEffect: { marketEtiquette: 'observed', enforceable: true },
    },
    {
        tag: PrivacyActionTag.SOUND_DAMPENING_MATS,
        need: NeedTag.PRIVACY,
        costEnergy: -0.12,
        costTime: 1.0,
        rewardSatisfaction: 0.65,
        rewardSecondary: { STABILITY: 0.3, CONTROL: 0.2 as any, HEALTH: 0.1 },
        tradeEffect: { hay_bales: '-N' as any, felt_mats: '-N' as any },
        socialImpact: { CALM: 0.3 as any },
        ownershipEffect: { roomAcoustics: 'dampened' },
    },
    {
        tag: PrivacyActionTag.CONTROL_VISITORS_LEDGER,
        need: NeedTag.PRIVACY,
        costEnergy: -0.1,
        costTime: 0.9,
        rewardSatisfaction: 0.65,
        rewardSecondary: { SECURITY: 0.3, CLARITY: 0.3, TRUST: 0.2 },
        tradeEffect: { parchment: -1, ink: -1 },
        socialImpact: { ABUSE: -0.1 as any, RESPECT: 0.1 },
        ownershipEffect: { visitorLog: 'active', accessScope: 'gate_clerk' },
        lawEffect: { entryRule: 'sign_in_required', enforceable: true },
    },
    {
        tag: PrivacyActionTag.SEALED_LETTER_SERVICE,
        need: NeedTag.PRIVACY,
        costEnergy: -0.08,
        costTime: 0.9,
        rewardSatisfaction: 0.7,
        rewardSecondary: { TRUST: 0.4, INTEGRITY: 0.3, STABILITY: 0.2 },
        tradeEffect: {
            wax: -1,
            ribbon: -1 | (0 as any),
            messenger_fee: -1 as any,
        },
        socialImpact: { GOSSIP: -0.15 as any, CREDIBILITY: 0.2 },
        ownershipEffect: { letterState: 'sealed', chainOfCustody: 'tracked' },
        lawEffect: { tamperPenalty: 'severe', enforceable: true },
    },
    {
        tag: PrivacyActionTag.MASK_IDENTITY_ATTIRE,
        need: NeedTag.PRIVACY,
        costEnergy: -0.06,
        costTime: 0.6,
        risk: 0.06, // могут спутать с злоумышленником
        rewardSatisfaction: 0.6,
        rewardSecondary: {
            CONTROL: 0.3 as any,
            SECURITY: 0.2,
            RESILIENCE: 0.1,
        },
        tradeEffect: { hood_cloak: -1 | (0 as any), veil: -1 | (0 as any) },
        socialImpact: { VISIBILITY: -0.2 as any, RESPECT: 0.1 },
        lawEffect: { maskRule: 'allowed_within_market', enforceable: true },
    },
    {
        tag: PrivacyActionTag.BATHING_SCHEDULE_SEPARATE,
        need: NeedTag.PRIVACY,
        costEnergy: -0.06,
        costTime: 0.7,
        rewardSatisfaction: 0.7,
        rewardSecondary: { RESPECT: 0.3, HEALTH: 0.2, STABILITY: 0.2 },
        requiresLocation: 'baths|river_hut',
        socialImpact: { CONFLICT: -0.1 as any, DIGNITY: 0.3 as any },
        lawEffect: { bathRoster: 'posted', enforceable: true },
    },
    {
        tag: PrivacyActionTag.WINDOW_SHUTTERS_PROTOCOL,
        need: NeedTag.PRIVACY,
        costEnergy: -0.05,
        costTime: 0.5,
        rewardSatisfaction: 0.55,
        rewardSecondary: {
            CONTROL: 0.25 as any,
            SECURITY: 0.2,
            STABILITY: 0.2,
        },
        tradeEffect: { shutters: -1 | (0 as any), cords: -1 | (0 as any) },
        socialImpact: { GAZE: -0.2 as any, RESPECT: 0.1 },
        ownershipEffect: { homeState: 'shutters_rule_active' },
        lawEffect: { nightPrivacy: 'observed', enforceable: true },
    },
    {
        tag: PrivacyActionTag.SECLUDED_PATH_MAPPING,
        need: NeedTag.PRIVACY,
        costEnergy: -0.12,
        costTime: 1.2,
        risk: 0.06,
        rewardSatisfaction: 0.7,
        rewardSecondary: { CONTROL: 0.3 as any, SECURITY: 0.2, CLARITY: 0.2 },
        tradeEffect: { parchment: -1, ink: -1, chalk: -1 },
        socialImpact: { CONFLICT: -0.05 as any },
        ownershipEffect: { routeMap: 'secluded_paths_marked' },
        lawEffect: { accessRule: 'private_paths_respected', enforceable: true },
    },
];
