import { ActionDefinition } from '../action-definition';
import { ProductivityActionTag } from '../action-tags';
import { NeedTag } from '../needs';

export const ProductivityActions: ActionDefinition[] = [
    {
        tag: ProductivityActionTag.MORNING_TALLY_AND_BRIEF,
        need: NeedTag.PRODUCTIVITY,
        costEnergy: -0.08,
        costTime: 0.8,
        rewardSatisfaction: 0.65,
        rewardSecondary: { CLARITY: 0.5, ORDER: 0.4, FOCUS: 0.3 },
        requiresLocation: 'workyard|guild_hall',
        tradeEffect: { chalk: -1, board_use: '+1' },
        socialImpact: { DISCIPLINE: 0.3, TRUST: 0.2 },
        ownershipEffect: { accessScope: 'task_board', grantAccess: true },
        lawEffect: { rosterPosted: 'yes', enforceable: true },
    },
    {
        tag: ProductivityActionTag.TASK_BOARD_PULL_TOKENS,
        need: NeedTag.PRODUCTIVITY,
        costEnergy: -0.06,
        costTime: 0.6,
        rewardSatisfaction: 0.6,
        rewardSecondary: { EFFICIENCY: 0.4, ORDER: 0.3, FOCUS: 0.3 },
        requiresLocation: 'task_board',
        tradeEffect: { tokens: '-move' },
        socialImpact: { ACCOUNTABILITY: 0.3 as any, CLARITY: 0.3 },
        ownershipEffect: { workItem: 'claimed' },
        lawEffect: { queueRule: 'pull_not_push', enforceable: true },
    },
    {
        tag: ProductivityActionTag.SET_WIP_LIMITS,
        need: NeedTag.PRODUCTIVITY,
        costEnergy: -0.08,
        costTime: 0.8,
        rewardSatisfaction: 0.65,
        rewardSecondary: { EFFICIENCY: 0.5, QUALITY: 0.3, ORDER: 0.4 },
        socialImpact: { DISCIPLINE: 0.4, FAIRNESS: 0.2 },
        lawEffect: { wipMax: 'posted', enforceable: true },
    },
    {
        tag: ProductivityActionTag.STANDARDIZE_WORK_STEPS,
        need: NeedTag.PRODUCTIVITY,
        costEnergy: -0.12,
        costTime: 1.2,
        rewardSatisfaction: 0.7,
        rewardSecondary: { QUALITY: 0.5, EFFICIENCY: 0.4, CLARITY: 0.4 },
        tradeEffect: { parchment: -1, ink: -1 },
        socialImpact: { INTEGRITY: 0.3, ORDER: 0.4 },
        ownershipEffect: { standardSheet: 'created', archive: 'yes' },
        lawEffect: { guildStandard: 'ratified', enforceable: true },
    },
    {
        tag: ProductivityActionTag.TOOLS_MAINTENANCE_ROTA,
        need: NeedTag.PRODUCTIVITY,
        costEnergy: -0.16,
        costTime: 1.4,
        rewardSatisfaction: 0.7,
        rewardSecondary: { EFFICIENCY: 0.4, QUALITY: 0.3, STABILITY: 0.3 },
        tradeEffect: { oil: -1, whetstone_wear: '-minor' },
        socialImpact: { RESPONSIBILITY: 0.3 as any, TRUST: 0.2 },
        ownershipEffect: { toolState: 'maintained' },
        lawEffect: { rota: 'logged', enforceable: true },
    },
    {
        tag: ProductivityActionTag.BENCH_LAYOUT_STREAMLINE,
        need: NeedTag.PRODUCTIVITY,
        costEnergy: -0.2,
        costTime: 1.6,
        rewardSatisfaction: 0.75,
        rewardSecondary: { EFFICIENCY: 0.6, ORDER: 0.4, SAFETY: 0.2 as any },
        requiresLocation: 'workshop',
        tradeEffect: { labor: '-rearrange', chalk: -1 },
        socialImpact: { COORDINATION: 0.3 as any, DISCIPLINE: 0.2 },
        ownershipEffect: { layout: 'streamlined' },
    },
    {
        tag: ProductivityActionTag.BATCH_PREP_MATERIALS,
        need: NeedTag.PRODUCTIVITY,
        costEnergy: -0.18,
        costTime: 1.6,
        rewardSatisfaction: 0.7,
        rewardSecondary: { EFFICIENCY: 0.5, STABILITY: 0.3, ORDER: 0.3 },
        tradeEffect: { raw_materials: '-N' as any, blanks: '+N' },
        socialImpact: { READINESS: 0.3 as any, TRUST: 0.1 },
        ownershipEffect: { storesLevel: 'raised' },
    },
    {
        tag: ProductivityActionTag.CROSS_TRAIN_PAIRING,
        need: NeedTag.PRODUCTIVITY,
        costEnergy: -0.16,
        costTime: 1.8,
        rewardSatisfaction: 0.75,
        rewardSecondary: { MASTERY: 0.4, RESILIENCE: 0.3, EFFICIENCY: 0.3 },
        requiresSkill: 'teaching|apprentice',
        socialImpact: { LOYALTY: 0.2, COMMUNITY: 0.2 },
        ownershipEffect: { accessScope: 'bench_guest', grantAccess: true },
        lawEffect: { apprenticeRoll: 'updated', enforceable: true },
    },
    {
        tag: ProductivityActionTag.PRIORITIZE_HIGH_IMPACT,
        need: NeedTag.PRODUCTIVITY,
        costEnergy: -0.1,
        costTime: 0.9,
        rewardSatisfaction: 0.7,
        rewardSecondary: { CLARITY: 0.5, WEALTH: 0.3, ORDER: 0.3 },
        socialImpact: { DISCIPLINE: 0.3, FAIRNESS: 0.2 },
        lawEffect: { priorityRule: 'value_first', enforceable: true },
    },
    {
        tag: ProductivityActionTag.REMOVE_BOTTLENECK,
        need: NeedTag.PRODUCTIVITY,
        costEnergy: -0.2,
        costTime: 1.6,
        risk: 0.1, // трения между бригадами
        rewardSatisfaction: 0.8,
        rewardSecondary: { EFFICIENCY: 0.6, STABILITY: 0.4, CLARITY: 0.3 },
        tradeEffect: { reassign_workers: '+2', idle_loss: '-1' },
        socialImpact: { COORDINATION: 0.4 as any, RESENTMENT: -0.1 },
        lawEffect: { dutyRota: 'amended', enforceable: true },
    },
    {
        tag: ProductivityActionTag.MEASURE_THROUGHPUT_TALLY,
        need: NeedTag.PRODUCTIVITY,
        costEnergy: -0.08,
        costTime: 0.8,
        rewardSatisfaction: 0.6,
        rewardSecondary: { CLARITY: 0.5, EFFICIENCY: 0.3, QUALITY: 0.2 },
        requiresItem: ['tally_sticks|abacus'],
        tradeEffect: { ink: '-1 | 0' as any },
        socialImpact: { TRANSPARENCY: 0.3 as any, TRUST: 0.2 },
        ownershipEffect: { tallyLog: 'updated' },
        lawEffect: { ledgerPolicy: 'accurate_entry', enforceable: true },
    },
    {
        tag: ProductivityActionTag.QUALITY_CHECK_AT_SOURCE,
        need: NeedTag.PRODUCTIVITY,
        costEnergy: -0.1,
        costTime: 1.0,
        rewardSatisfaction: 0.7,
        rewardSecondary: { QUALITY: 0.6, EFFICIENCY: 0.3, WASTE: -0.2 as any },
        requiresLocation: 'workbench',
        socialImpact: { INTEGRITY: 0.3, RESPECT: 0.2 },
        lawEffect: { defectStopRule: 'worker_can_stop', enforceable: true },
    },
    {
        tag: ProductivityActionTag.MIDDAY_SYNCH_AND_REALLOC,
        need: NeedTag.PRODUCTIVITY,
        costEnergy: -0.1,
        costTime: 0.9,
        rewardSatisfaction: 0.65,
        rewardSecondary: { EFFICIENCY: 0.4, ORDER: 0.3, CLARITY: 0.3 },
        requiresLocation: 'workyard',
        socialImpact: { COORDINATION: 0.4 as any, TRUST: 0.2 },
        ownershipEffect: { accessScope: 'task_board', grantAccess: true },
    },
    {
        tag: ProductivityActionTag.BUFFER_STOCK_ESTABLISH,
        need: NeedTag.PRODUCTIVITY,
        costEnergy: -0.18,
        costTime: 1.6,
        rewardSatisfaction: 0.7,
        rewardSecondary: { STABILITY: 0.5, RESILIENCE: 0.4, EFFICIENCY: 0.2 },
        tradeEffect: { blanks: '+N', storage_space: '-capacity' },
        socialImpact: { READINESS: 0.3 as any },
        ownershipEffect: { storeState: 'buffered' },
        lawEffect: { storeLedger: 'updated', enforceable: true },
    },
    {
        tag: ProductivityActionTag.SHIFT_HANDOFF_RITUAL,
        need: NeedTag.PRODUCTIVITY,
        costEnergy: -0.08,
        costTime: 0.8,
        rewardSatisfaction: 0.65,
        rewardSecondary: { ORDER: 0.4, CLARITY: 0.4, QUALITY: 0.3 },
        requiresLocation: 'workbench|gate',
        tradeEffect: { seal_wax: '-1 | 0' as any },
        socialImpact: { TRUST: 0.3, DISCIPLINE: 0.3 },
        ownershipEffect: {
            logbook: 'signed',
            accessScope: 'shift_area',
            grantAccess: true,
        },
        lawEffect: { handoffRule: 'required', enforceable: true },
    },
    {
        tag: ProductivityActionTag.FAIR_REWARD_DISTRIBUTION,
        need: NeedTag.PRODUCTIVITY,
        costEnergy: -0.1,
        costTime: 1.0,
        rewardSatisfaction: 0.8,
        rewardSecondary: { FAIRNESS: 0.6, MORALE: 0.5, STABILITY: 0.3 },
        requiresLocation: 'hall|yard',
        tradeEffect: { coin_purse: '-distributed' },
        socialImpact: { TRUST: 0.4, LOYALTY: 0.3, RESENTMENT: -0.2 },
        lawEffect: { rewardLedger: 'posted', enforceable: true },
    },
];
