import { ActionDefinition } from '../action-definition';
import { QualityActionTag } from '../action-tags';
import { NeedTag } from '../needs';

export const QualityActions: ActionDefinition[] = [
    {
        tag: QualityActionTag.SPEC_DEFINE_ACCEPTANCE,
        need: NeedTag.QUALITY,
        costEnergy: -0.12,
        costTime: 1.2,
        rewardSatisfaction: 0.65,
        rewardSecondary: { CLARITY: 0.5, ORDER: 0.4, FAIRNESS: 0.3 },
        tradeEffect: { parchment: -1, ink: -1 },
        socialImpact: { INTEGRITY: 0.3, TRUST: 0.2 },
        ownershipEffect: { specSheet: 'created', archive: 'yes' },
        lawEffect: { standardCharter: 'ratified', enforceable: true },
    },
    {
        tag: QualityActionTag.SELECT_PROPER_MATERIAL,
        need: NeedTag.QUALITY,
        costEnergy: -0.14,
        costTime: 1.0,
        rewardSatisfaction: 0.6,
        rewardSecondary: { EFFICIENCY: 0.3, STABILITY: 0.2, WEALTH: 0.2 },
        tradeEffect: { raw_good: '+N', raw_bad: '-N' },
        socialImpact: { RESPONSIBILITY: 0.2 as any },
        ownershipEffect: { storesQuality: 'improved' },
    },
    {
        tag: QualityActionTag.CALIBRATE_TOOLS,
        need: NeedTag.QUALITY,
        costEnergy: -0.12,
        costTime: 1.0,
        rewardSatisfaction: 0.65,
        rewardSecondary: { EFFICIENCY: 0.3, SAFETY: 0.2 as any, ORDER: 0.2 },
        tradeEffect: {
            calibration_weights: -1 | (0 as any),
            oil: -1 | (0 as any),
        },
        socialImpact: { DISCIPLINE: 0.3, TRUST: 0.1 },
        ownershipEffect: { toolCal: 'ok', dueDate: 'set' },
        lawEffect: { measureSeal: 'stamped', enforceable: true },
    },
    {
        tag: QualityActionTag.FIRST_ARTICLE_CHECK,
        need: NeedTag.QUALITY,
        costEnergy: -0.16,
        costTime: 1.2,
        rewardSatisfaction: 0.7,
        rewardSecondary: { CLARITY: 0.4, EFFICIENCY: 0.3, INTEGRITY: 0.3 },
        requiresLocation: 'workbench|inspection_table',
        socialImpact: { TRANSPARENCY: 0.3 as any },
        ownershipEffect: { masterSample: 'approved|revised' },
        lawEffect: { firstArticleRecord: 'filed', enforceable: true },
    },
    {
        tag: QualityActionTag.IN_PROCESS_INSPECTION,
        need: NeedTag.QUALITY,
        costEnergy: -0.14,
        costTime: 1.2,
        rewardSatisfaction: 0.65,
        rewardSecondary: { EFFICIENCY: 0.4, ORDER: 0.3, STABILITY: 0.3 },
        socialImpact: { TRUST: 0.2, COORDINATION: 0.2 as any },
        ownershipEffect: { lotStatus: 'hold|release' },
    },
    {
        tag: QualityActionTag.STOP_AND_FIX_RULE,
        need: NeedTag.QUALITY,
        costEnergy: -0.1,
        costTime: 0.8,
        rewardSatisfaction: 0.7,
        rewardSecondary: { INTEGRITY: 0.4, SAFETY: 0.2 as any, FAIRNESS: 0.2 },
        socialImpact: { RESPECT: 0.2, BLAME: -0.1 as any },
        lawEffect: { defectStopRule: 'worker_can_stop', enforceable: true },
    },
    {
        tag: QualityActionTag.SCRAP_AND_REWORK,
        need: NeedTag.QUALITY,
        costEnergy: -0.2,
        costTime: 1.6,
        rewardSatisfaction: 0.6,
        rewardSecondary: { ORDER: 0.3, WEALTH: -0.2, EFFICIENCY: 0.2 },
        tradeEffect: { scrap: '+N', rework_hours: '+N' },
        socialImpact: { RESPONSIBILITY: 0.3 as any, LEARNING: 0.2 as any },
        ownershipEffect: { lotState: 'rework', ledger: 'updated' },
    },
    {
        tag: QualityActionTag.POKA_YOKE_GUARDS,
        need: NeedTag.QUALITY,
        costEnergy: -0.18,
        costTime: 1.6,
        rewardSatisfaction: 0.75,
        rewardSecondary: {
            EFFICIENCY: 0.5,
            STABILITY: 0.4,
            SAFETY: 0.3 as any,
        },
        tradeEffect: { jigs: -1, guards: -1, nails: -1 },
        socialImpact: { DISCIPLINE: 0.3, TRUST: 0.2 },
        ownershipEffect: { fixtureState: 'installed' },
    },
    {
        tag: QualityActionTag.CLEAN_WORK_SURFACES,
        need: NeedTag.QUALITY,
        costEnergy: -0.12,
        costTime: 1.0,
        rewardSatisfaction: 0.6,
        rewardSecondary: { ORDER: 0.5, EFFICIENCY: 0.3, HYGIENE: 0.3 },
        tradeEffect: { linen: -1, soap: -1 | (0 as any) },
        socialImpact: { DIGNITY: 0.2 as any },
        ownershipEffect: { benchState: 'clean' },
    },
    {
        tag: QualityActionTag.TOOL_EDGE_MAINTENANCE,
        need: NeedTag.QUALITY,
        costEnergy: -0.14,
        costTime: 1.0,
        rewardSatisfaction: 0.65,
        rewardSecondary: {
            EFFICIENCY: 0.3,
            SAFETY: 0.2 as any,
            STABILITY: 0.2,
        },
        tradeEffect: { whetstone_wear: '-minor', oil: -1 | (0 as any) },
        socialImpact: { RESPONSIBILITY: 0.2 as any },
        ownershipEffect: { toolSharp: 'ok' },
    },
    {
        tag: QualityActionTag.FINAL_INSPECTION_STAMP,
        need: NeedTag.QUALITY,
        costEnergy: -0.12,
        costTime: 1.2,
        rewardSatisfaction: 0.75,
        rewardSecondary: { INTEGRITY: 0.4, REPUTATION: 0.3, WEALTH: 0.2 },
        requiresLocation: 'inspection_table',
        tradeEffect: { seal_wax: -1 | (0 as any) },
        socialImpact: { TRUST: 0.3, STATUS: 0.2 },
        ownershipEffect: { stamp: 'applied', provenance: 'traceable' },
        lawEffect: { hallmarkRoll: 'updated', enforceable: true },
    },
    {
        tag: QualityActionTag.DEFECT_LOG_LEDGER,
        need: NeedTag.QUALITY,
        costEnergy: -0.1,
        costTime: 0.9,
        rewardSatisfaction: 0.6,
        rewardSecondary: { CLARITY: 0.5, ORDER: 0.4, RESILIENCE: 0.2 },
        tradeEffect: { parchment: -1, ink: -1 },
        socialImpact: { TRANSPARENCY: 0.3 as any, TRUST: 0.2 },
        ownershipEffect: { defectLedger: 'updated' },
        lawEffect: { ledgerPolicy: 'accurate_entry', enforceable: true },
    },
    {
        tag: QualityActionTag.ROOT_CAUSE_CIRCLE,
        need: NeedTag.QUALITY,
        costEnergy: -0.16,
        costTime: 1.4,
        rewardSatisfaction: 0.8,
        rewardSecondary: { CLARITY: 0.5, EFFICIENCY: 0.3, STABILITY: 0.3 },
        requiresLocation: 'hall|workyard',
        socialImpact: { COHESION: 0.3, FAIRNESS: 0.2 },
        ownershipEffect: { actionItems: 'issued' },
    },
    {
        tag: QualityActionTag.TRAIN_ON_STANDARD,
        need: NeedTag.QUALITY,
        costEnergy: -0.16,
        costTime: 1.6,
        rewardSatisfaction: 0.75,
        rewardSecondary: { MASTERY: 0.4, EFFICIENCY: 0.3, INTEGRITY: 0.3 },
        requiresLocation: 'workshop|yard',
        tradeEffect: { training_materials: -1 },
        socialImpact: { RESPECT: 0.2, TRUST: 0.2 },
        ownershipEffect: { accessScope: 'training_room', grantAccess: true },
        lawEffect: { trainingRoster: 'logged', enforceable: true },
    },
    {
        tag: QualityActionTag.SUPPLIER_AUDIT_VISIT,
        need: NeedTag.QUALITY,
        costEnergy: -0.2,
        costTime: 2.0,
        risk: 0.1,
        rewardSatisfaction: 0.8,
        rewardSecondary: { STABILITY: 0.4, WEALTH: 0.2, CONTROL: 0.2 },
        tradeEffect: { travel_supplies: -1, sample_fee: -1 | (0 as any) },
        socialImpact: { NETWORK: 0.2, RESPECT: 0.2 },
        ownershipEffect: { supplierStatus: 'audited' },
        lawEffect: { auditRoll: 'filed', enforceable: true },
    },
    {
        tag: QualityActionTag.CUSTOMER_FEEDBACK_LOOP,
        need: NeedTag.QUALITY,
        costEnergy: -0.14,
        costTime: 1.2,
        rewardSatisfaction: 0.75,
        rewardSecondary: { CLARITY: 0.5, TRUST: 0.3, WEALTH: 0.2 },
        requiresLocation: 'market|hall',
        socialImpact: { REPUTATION: 0.3, FAIRNESS: 0.2 },
        ownershipEffect: { feedbackLog: 'updated' },
        lawEffect: { complaintDesk: 'active', enforceable: true },
    },
];
