import { ActionDefinition } from '../action-definition';
import { ResilienceActionTag } from '../action-tags';
import { NeedTag } from '../needs';

export const ResilienceActions: ActionDefinition[] = [
    {
        tag: ResilienceActionTag.EMERGENCY_DRILL,
        need: NeedTag.RESILIENCE,
        costEnergy: -0.16,
        costTime: 1.2,
        risk: 0.06, // мелкие травмы/паника
        rewardSatisfaction: 0.75,
        rewardSecondary: {
            READINESS: 0.6 as any,
            STABILITY: 0.4,
            COURAGE: 0.2,
        },
        requiresLocation: 'hall|yard|camp',
        socialImpact: { TRUST: 0.2, COHESION: 0.3 as any },
        lawEffect: { drillRule: 'monthly_required', enforceable: true },
        ownershipEffect: { musterPoints: 'marked' },
    },
    {
        tag: ResilienceActionTag[' STOCKPILE_ESSENTIALS'],
        need: NeedTag.RESILIENCE,
        costEnergy: -0.2,
        costTime: 1.6,
        rewardSatisfaction: 0.8,
        rewardSecondary: { STABILITY: 0.6, SECURITY: 0.3, WEALTH: 0.2 },
        tradeEffect: { grain: '+N', salt: '+N', bandages: '+N' },
        socialImpact: { TRUST: 0.2, PANIC: -0.2 as any },
        ownershipEffect: { storesLevel: 'strategic', rotation: 'set' },
        lawEffect: { rationPolicy: 'defined', enforceable: true },
    },
    {
        tag: ResilienceActionTag.DIVERSIFY_CROPS_CRAFTS,
        need: NeedTag.RESILIENCE,
        costEnergy: -0.22,
        costTime: 2.0,
        rewardSatisfaction: 0.8,
        rewardSecondary: { STABILITY: 0.5, WEALTH: 0.3, HEALTH: 0.2 },
        requiresLocation: 'fields|workshops',
        socialImpact: { INNOVATION_REP: 0.2, COMMUNITY: 0.2 },
        ownershipEffect: { portfolio: 'diversified' },
        lawEffect: { seedRights: 'granted', enforceable: true },
    },
    {
        tag: ResilienceActionTag.CROSS_TRAIN_ROLES,
        need: NeedTag.RESILIENCE,
        costEnergy: -0.18,
        costTime: 1.6,
        rewardSatisfaction: 0.75,
        rewardSecondary: {
            READINESS: 0.5 as any,
            STABILITY: 0.4,
            MASTERY: 0.3,
        },
        requiresLocation: 'guild_hall|yard',
        socialImpact: { COHESION: 0.3, RESPECT: 0.2 },
        ownershipEffect: { skillsMatrix: 'redundancy_added' },
    },
    {
        tag: ResilienceActionTag.MUTUAL_AID_PACT,
        need: NeedTag.RESILIENCE,
        costEnergy: -0.14,
        costTime: 1.4,
        risk: 0.08, // асимметрия ожиданий
        rewardSatisfaction: 0.8,
        rewardSecondary: { COMMUNITY: 0.5, TRUST: 0.4, STABILITY: 0.4 },
        requiresLocation: 'hall|neighbor_village',
        socialImpact: { NETWORK: 0.4, LOYALTY: 0.2 },
        lawEffect: { pactCharter: 'sealed', enforceable: true },
        ownershipEffect: { accessScope: 'mutual_aid', grantAccess: true },
    },
    {
        tag: ResilienceActionTag.REPAIR_SPRINT,
        need: NeedTag.RESILIENCE,
        costEnergy: -0.22,
        costTime: 1.6,
        rewardSatisfaction: 0.85,
        rewardSecondary: { STABILITY: 0.5, PRODUCTIVITY: 0.3, MORALE: 0.2 },
        requiresLocation: 'gate|roof|well|bridge',
        tradeEffect: {
            timber: '-N' as any,
            nails: '-N' as any,
            pitch: -1 | (0 as any),
        },
        socialImpact: { COMMUNITY: 0.3, RESPECT: 0.2 },
        ownershipEffect: { criticalAssets: 'restored' },
    },
    {
        tag: ResilienceActionTag.FIREBREAK_AND_CLEARING,
        need: NeedTag.RESILIENCE,
        costEnergy: -0.24,
        costTime: 1.8,
        rewardSatisfaction: 0.8,
        rewardSecondary: { SECURITY: 0.4, STABILITY: 0.4, HEALTH: 0.1 },
        requiresLocation: 'forest_edge|fields',
        tradeEffect: { axes_wear: '-minor', labor: '-N' as any },
        socialImpact: { READINESS: 0.3 as any, TRUST: 0.2 },
        ownershipEffect: { firebreaks: 'cut' },
        lawEffect: { burnBan: 'posted', enforceable: true },
    },
    {
        tag: ResilienceActionTag.FLOOD_LEVEE_DITCHES,
        need: NeedTag.RESILIENCE,
        costEnergy: -0.26,
        costTime: 2.0,
        rewardSatisfaction: 0.85,
        rewardSecondary: { SECURITY: 0.5, STABILITY: 0.5, WEALTH: 0.2 },
        requiresLocation: 'river_bank|lowlands',
        tradeEffect: { shovels_wear: '-minor', stakes: '-N' as any },
        socialImpact: { COMMUNITY: 0.3, TRUST: 0.2 },
        ownershipEffect: { levees: 'raised', ditches: 'dug' },
    },
    {
        tag: ResilienceActionTag.QUARANTINE_PROTOCOL,
        need: NeedTag.RESILIENCE,
        costEnergy: -0.18,
        costTime: 1.2,
        risk: 0.12, // социальная напряжённость
        rewardSatisfaction: 0.8,
        rewardSecondary: { HEALTH: 0.6, SECURITY: 0.3, STABILITY: 0.3 },
        requiresLocation: 'infirmary|gate',
        socialImpact: { FEAR: -0.1, TRUST: 0.2 },
        lawEffect: { quarantine: 'active', enforceable: true },
        ownershipEffect: { accessScope: 'isolation_ward', grantAccess: true },
    },
    {
        tag: ResilienceActionTag.BACKUP_TOOLS_AND_PARTS,
        need: NeedTag.RESILIENCE,
        costEnergy: -0.16,
        costTime: 1.2,
        rewardSatisfaction: 0.7,
        rewardSecondary: { STABILITY: 0.4, PRODUCTIVITY: 0.3, SECURITY: 0.2 },
        tradeEffect: { spare_parts: '+N', tools: '+N' },
        socialImpact: { TRUST: 0.2 },
        ownershipEffect: { redundancyLevel: 'raised' },
    },
    {
        tag: ResilienceActionTag.SAFE_WATER_CACHE,
        need: NeedTag.RESILIENCE,
        costEnergy: -0.14,
        costTime: 1.2,
        rewardSatisfaction: 0.75,
        rewardSecondary: { HEALTH: 0.5, STABILITY: 0.4, SECURITY: 0.2 },
        requiresLocation: 'well_house|cool_cellar',
        tradeEffect: { barrels: '-N' as any, lime: -1 | (0 as any) },
        socialImpact: { TRUST: 0.2, PANIC: -0.1 as any },
        ownershipEffect: { waterCache: 'sealed' },
    },
    {
        tag: ResilienceActionTag.RISK_REGISTER_COUNCIL,
        need: NeedTag.RESILIENCE,
        costEnergy: -0.12,
        costTime: 1.0,
        rewardSatisfaction: 0.7,
        rewardSecondary: { CLARITY: 0.5, STABILITY: 0.4, TRUST: 0.2 },
        requiresLocation: 'hall|council_chamber',
        socialImpact: { TRANSPARENCY: 0.3 as any, COHESION: 0.2 },
        ownershipEffect: { riskRegister: 'updated', mitigation: 'assigned' },
    },
    {
        tag: ResilienceActionTag.EVACUATION_ROUTES_MAP,
        need: NeedTag.RESILIENCE,
        costEnergy: -0.12,
        costTime: 1.0,
        rewardSatisfaction: 0.75,
        rewardSecondary: { READINESS: 0.5 as any, SECURITY: 0.3, CLARITY: 0.3 },
        tradeEffect: { parchment: -1, ink: -1, signs: '-N' as any },
        socialImpact: { PANIC: -0.2 as any, TRUST: 0.2 },
        ownershipEffect: { evacMap: 'posted', rallyPoints: 'named' },
    },
    {
        tag: ResilienceActionTag.WORKLOAD_ROTATION_PLAN,
        need: NeedTag.RESILIENCE,
        costEnergy: -0.1,
        costTime: 0.9,
        rewardSatisfaction: 0.7,
        rewardSecondary: { HEALTH: 0.3, STABILITY: 0.3, MORALE: 0.3 },
        socialImpact: { FAIRNESS: 0.3, RESENTMENT: -0.1 },
        lawEffect: { rota: 'fatigue_limits_posted', enforceable: true },
        ownershipEffect: { dutyRoster: 'rotating' },
    },
    {
        tag: ResilienceActionTag.COPING_RITUALS_CIRCLE,
        need: NeedTag.RESILIENCE,
        costEnergy: -0.1,
        costTime: 1.0,
        rewardSatisfaction: 0.8,
        rewardSecondary: { MORALE: 0.5, COMMUNITY: 0.4, HEALTH: 0.2 },
        requiresLocation: 'hearth|temple|grove',
        socialImpact: { EMPATHY: 0.4 as any, HOPE: 0.3 as any },
        ownershipEffect: { memoryLog: 'healed_entry' },
    },
    {
        tag: ResilienceActionTag.CONTINGENCY_FUND,
        need: NeedTag.RESILIENCE,
        costEnergy: -0.08,
        costTime: 0.8,
        rewardSatisfaction: 0.75,
        rewardSecondary: { STABILITY: 0.5, WEALTH: 0.4, TRUST: 0.2 },
        tradeEffect: { coin: '-set_aside' },
        socialImpact: { SECURITY: 0.2, COMMUNITY: 0.2 },
        ownershipEffect: {
            treasuryReserve: 'earmarked',
            withdrawRules: 'strict',
        },
        lawEffect: { reserveCharter: 'sealed', enforceable: true },
    },
];
