import { ActionDefinition } from '../action-definition';
import { ActionTags } from '../action-tags';
import { NeedTag } from '../needs';

export const RestActions: ActionDefinition[] = [
    {
        tag: ActionTags.SIT,
        need: NeedTag.REST,
        costEnergy: -0.1,
        costTime: 0.5,
        rewardSatisfaction: 0.1,
        rewardSecondary: { COMFORT: 0.1 },
        locationType: 'any',
    },
    {
        tag: ActionTags.LIE_DOWN,
        need: NeedTag.REST,
        costEnergy: -0.15,
        costTime: 1,
        risk: 0.05,
        rewardSatisfaction: 0.2,
        rewardSecondary: { HEALTH: 0.1 },
        locationType: 'camp',
    },
    {
        tag: ActionTags.NAP,
        need: NeedTag.REST,
        costEnergy: -0.25,
        costTime: 2,
        risk: 0.05,
        rewardSatisfaction: 0.4,
        rewardSecondary: { MOOD: 0.2 },
        locationType: 'any',
    },
    {
        tag: ActionTags.SLEEP,
        need: NeedTag.REST,
        costEnergy: -0.4,
        costTime: 6,
        risk: 0.1,
        rewardSatisfaction: 1.0,
        rewardSecondary: { HEALTH: 0.5, MOOD: 0.4 },
        locationType: 'shelter',
    },
    {
        tag: ActionTags.REST_AT_HOME,
        need: NeedTag.REST,
        costEnergy: -0.5,
        costTime: 8,
        rewardSatisfaction: 1.2,
        rewardSecondary: { HEALTH: 0.6, MOOD: 0.5 },
        locationType: 'home',
        socialImpact: { communication: 0.1 },
    },
    {
        tag: ActionTags.REST_FIELD,
        need: NeedTag.REST,
        costEnergy: -0.2,
        costTime: 3,
        risk: 0.4,
        rewardSatisfaction: 0.3,
        rewardSecondary: { HEALTH: -0.1 },
        locationType: 'field',
    },
    {
        tag: ActionTags.REST_BY_FIRE,
        need: NeedTag.REST,
        costEnergy: -0.25,
        costTime: 2,
        risk: 0.05,
        rewardSatisfaction: 0.6,
        rewardSecondary: { COMFORT: 0.4, SOCIAL: 0.2 },
        locationType: 'campfire',
    },
    {
        tag: ActionTags.MEDITATE,
        need: NeedTag.REST,
        costEnergy: -0.2,
        costTime: 1,
        risk: 0,
        rewardSatisfaction: 0.5,
        rewardSecondary: { FOCUS: 0.6 },
        skillRequired: 'Discipline',
        locationType: 'quiet',
    },
    {
        tag: ActionTags.RELAX,
        need: NeedTag.REST,
        costEnergy: -0.15,
        costTime: 1,
        rewardSatisfaction: 0.3,
        rewardSecondary: { MOOD: 0.3 },
        locationType: 'any',
    },
    {
        tag: ActionTags.SOCIALIZE_FOR_REST,
        need: NeedTag.REST,
        costEnergy: -0.1,
        costTime: 2,
        rewardSatisfaction: 0.5,
        rewardSecondary: { SOCIAL: 0.5, MOOD: 0.3 },
        locationType: 'village',
        visibleToOthers: true,
    },
    {
        tag: ActionTags.BATHING,
        need: NeedTag.REST,
        costEnergy: -0.2,
        costTime: 1.5,
        rewardSatisfaction: 0.4,
        rewardSecondary: { HYGIENE: 0.4, COMFORT: 0.3 },
        locationType: 'river',
    },
    {
        tag: ActionTags.REST_GUARDED,
        need: NeedTag.REST,
        costEnergy: -0.3,
        costTime: 6,
        risk: 0.05,
        rewardSatisfaction: 1.1,
        rewardSecondary: { TRUST: 0.4 },
        locationType: 'camp',
        groupAffinity: 0.4,
    },
    {
        tag: ActionTags.REST_IN_SHADE,
        need: NeedTag.REST,
        costEnergy: -0.2,
        costTime: 1.5,
        rewardSatisfaction: 0.3,
        rewardSecondary: { COMFORT: 0.3 },
        locationType: 'outdoor',
    },
    {
        tag: ActionTags.DREAM,
        need: NeedTag.REST,
        costEnergy: -0.4,
        costTime: 7,
        rewardSatisfaction: 0.9,
        rewardSecondary: { INSPIRATION: 0.5, FAITH: 0.3 },
        locationType: 'shelter',
    },
];
