import { StabilityActionTag } from '../action-tags';
import { ActionDefinition } from '../action-definition';
import { NeedTag } from '../needs';

export const StabilityActions: ActionDefinition[] = [
    {
        tag: StabilityActionTag.MAINTAIN_STORAGE,
        need: NeedTag.STABILITY,
        costEnergy: -0.3,
        costTime: 2,
        rewardSatisfaction: 0.7,
        rewardSecondary: { SECURITY: 0.4, CONTROL: 0.3 },
        requiresItem: ['tools'],
        requiresLocation: 'granary',
        requiresSkill: 'organization',
    },
    {
        tag: StabilityActionTag.REPAIR_TOOLS,
        need: NeedTag.STABILITY,
        costEnergy: -0.2,
        costTime: 1,
        rewardSatisfaction: 0.4,
        rewardSecondary: { CONTROL: 0.2, MASTERY: 0.2 },
        requiresItem: ['broken_tool', 'iron'],
        requiresSkill: 'crafting',
    },
    {
        tag: StabilityActionTag.HOLD_COUNCIL,
        need: NeedTag.STABILITY,
        costEnergy: -0.5,
        costTime: 3,
        rewardSatisfaction: 0.8,
        rewardSecondary: { COMMUNITY: 0.6, LAW: 0.5 },
        requiresLocation: 'hall',
        targetType: 'GROUP',
        requiresSkill: 'leadership',
    },
    {
        tag: StabilityActionTag.FOLLOW_TRADITION,
        need: NeedTag.STABILITY,
        costEnergy: -0.1,
        costTime: 1,
        rewardSatisfaction: 0.6,
        rewardSecondary: { TRADITION: 0.7, SPIRIT: 0.3 },
        moralWeight: 0.5,
    },
    {
        tag: StabilityActionTag.MANAGE_SUPPLIES,
        need: NeedTag.STABILITY,
        costEnergy: -0.4,
        costTime: 2,
        rewardSatisfaction: 0.8,
        rewardSecondary: { SECURITY: 0.5, CONTROL: 0.4 },
        requiresSkill: 'logistics',
    },
    {
        tag: StabilityActionTag.RESTORE_ORDER,
        need: NeedTag.STABILITY,
        costEnergy: -0.3,
        costTime: 1.5,
        rewardSatisfaction: 0.7,
        rewardSecondary: { LAW: 0.6, CONTROL: 0.5 },
        requiresSkill: 'leadership',
        targetType: 'GROUP',
    },
    {
        tag: StabilityActionTag.MEDIATE_CONFLICT,
        need: NeedTag.STABILITY,
        costEnergy: -0.2,
        costTime: 2,
        rewardSatisfaction: 0.6,
        rewardSecondary: { TRUST: 0.5, COMMUNITY: 0.3 },
        requiresSkill: 'diplomacy',
    },
    {
        tag: StabilityActionTag.HOLD_CEREMONY,
        need: NeedTag.STABILITY,
        costEnergy: -0.4,
        costTime: 3,
        rewardSatisfaction: 0.8,
        rewardSecondary: { COMMUNITY: 0.5, TRADITION: 0.6 },
        requiresLocation: 'temple',
    },
    {
        tag: StabilityActionTag.KEEP_RECORDS,
        need: NeedTag.STABILITY,
        costEnergy: -0.15,
        costTime: 1,
        rewardSatisfaction: 0.5,
        rewardSecondary: { KNOWLEDGE: 0.3, CONTROL: 0.2 },
        requiresItem: ['parchment', 'ink'],
        requiresSkill: 'writing',
    },
    {
        tag: StabilityActionTag.PLANT_SEASONAL_CROPS,
        need: NeedTag.STABILITY,
        costEnergy: -0.6,
        costTime: 4,
        rewardSatisfaction: 0.7,
        rewardSecondary: { FOOD: 0.5, TRADITION: 0.3 },
        requiresSkill: 'farming',
        locationType: 'fields',
    },
];
