import { ActionDefinition } from '../action-definition';
import { StressActionTag } from '../action-tags';
import { NeedTag } from '../needs';

export const StressActions: ActionDefinition[] = [
    {
        tag: StressActionTag.BREATHING_DRILL,
        need: NeedTag.STRESS,
        costEnergy: -0.02,
        costTime: 0.25,
        rewardSatisfaction: 0.5,
        rewardSecondary: { RESILIENCE: 0.3, FOCUS: 0.2, CLARITY: 0.2 },
        requiresLocation: 'quiet_corner|hearth',
        socialImpact: { CALM: 0.3 as any },
    },
    {
        tag: StressActionTag.WALK_SHORT_SOLO,
        need: NeedTag.STRESS,
        costEnergy: -0.06,
        costTime: 0.6,
        rewardSatisfaction: 0.65,
        rewardSecondary: { HEALTH: 0.2, RESILIENCE: 0.3, PRIVACY: 0.2 },
        requiresLocation: 'garden|path|river_bank',
        socialImpact: { CONFLICT: -0.05 as any, MOOD: 0.2 as any },
        ownershipEffect: { routeUse: 'solo_walk' },
    },
    {
        tag: StressActionTag.QUIET_TEATIME,
        need: NeedTag.STRESS,
        costEnergy: -0.04,
        costTime: 0.4,
        rewardSatisfaction: 0.6,
        rewardSecondary: { HEALTH: 0.2, MORALE: 0.2, PRIVACY: 0.2 },
        tradeEffect: { herbs: '-1 | 0' as any, honey: '-1 | 0' as any },
        socialImpact: { CALM: 0.3 as any },
        ownershipEffect: { kettleState: 'steeped' },
    },
    {
        tag: StressActionTag.STRETCH_AND_LOOSEN,
        need: NeedTag.STRESS,
        costEnergy: -0.05,
        costTime: 0.5,
        rewardSatisfaction: 0.55,
        rewardSecondary: { HEALTH: 0.3, RESILIENCE: 0.2, FOCUS: 0.1 },
        requiresLocation: 'yard|workroom',
        socialImpact: { TENSION: -0.2 as any },
    },
    {
        tag: StressActionTag.JOURNAL_UNLOAD,
        need: NeedTag.STRESS,
        costEnergy: -0.06,
        costTime: 0.6,
        rewardSatisfaction: 0.65,
        rewardSecondary: { CLARITY: 0.4, PRIVACY: 0.3, RESILIENCE: 0.2 },
        tradeEffect: { parchment: '-1 | 0' as any, ink: '-1 | 0' as any },
        socialImpact: { RUMORS: -0.05 as any },
        ownershipEffect: { diary: 'entry_added' },
    },
    {
        tag: StressActionTag.POWER_NAP,
        need: NeedTag.STRESS,
        costEnergy: +0.12, // восстанавливает энергию (см. ENERGY)
        costTime: 0.6,
        rewardSatisfaction: 0.7,
        rewardSecondary: { HEALTH: 0.2, RESILIENCE: 0.3, MORALE: 0.2 },
        requiresLocation: 'bunks|hearth',
        socialImpact: { PRODUCTIVITY: 0.05 },
        ownershipEffect: { berthUse: 'short_rest' },
    },
    {
        tag: StressActionTag.SWITCH_TASK_SIMPLE,
        need: NeedTag.STRESS,
        costEnergy: -0.02,
        costTime: 0.4,
        rewardSatisfaction: 0.55,
        rewardSecondary: { PRODUCTIVITY: 0.2, FOCUS: 0.2, MORALE: 0.2 },
        socialImpact: { OVERWHELM: -0.2 as any },
        ownershipEffect: { taskState: 'context_switched' },
    },
    {
        tag: StressActionTag.DELEGATE_NONCRITICAL,
        need: NeedTag.STRESS,
        costEnergy: -0.02,
        costTime: 0.5,
        rewardSatisfaction: 0.6,
        rewardSecondary: {
            ACCOUNTABILITY: 0.2 as any,
            STABILITY: 0.2,
            TRUST: 0.2,
        },
        requiresSkill: 'leadership|negotiation',
        socialImpact: { BURDEN: -0.3 as any, RESPECT: 0.1 },
        ownershipEffect: { taskOwner: 'reassigned' },
    },
    {
        tag: StressActionTag.BOUNDARY_SAY_NO,
        need: NeedTag.STRESS,
        costEnergy: -0.02,
        costTime: 0.3,
        risk: 0.06, // может задеть другого
        rewardSatisfaction: 0.65,
        rewardSecondary: { PRIVACY: 0.3, CONTROL: 0.3 as any, RESILIENCE: 0.2 },
        socialImpact: { RESPECT: 0.2, CONFLICT: -0.05 as any },
        lawEffect: { boundaryNote: 'posted', enforceable: true },
    },
    {
        tag: StressActionTag.SOCIAL_VENT_SAFE,
        need: NeedTag.STRESS,
        costEnergy: -0.06,
        costTime: 0.7,
        rewardSatisfaction: 0.7,
        rewardSecondary: { COMMUNITY: 0.3, TRUST: 0.3, RESILIENCE: 0.3 },
        requiresLocation: 'hearth|hall',
        socialImpact: { EMPATHY: 0.4 as any, GOSSIP: -0.1 as any },
        ownershipEffect: { circleState: 'vent_done' },
    },
    {
        tag: StressActionTag.MUSIC_CALM_SESSION,
        need: NeedTag.STRESS,
        costEnergy: -0.04,
        costTime: 0.6,
        rewardSatisfaction: 0.65,
        rewardSecondary: { HEALTH: 0.1, JOY: 0.3 as any, MORALE: 0.3 },
        requiresItem: ['flute|lyre|drum_soft'],
        socialImpact: { CALM: 0.4 as any },
    },
    {
        tag: StressActionTag.TIDY_MICRO_AREA,
        need: NeedTag.STRESS,
        costEnergy: -0.08,
        costTime: 0.6,
        rewardSatisfaction: 0.6,
        rewardSecondary: { ORDER: 0.4, CONTROL: 0.2 as any, PRODUCTIVITY: 0.1 },
        socialImpact: { DIGNITY: 0.2 as any },
        ownershipEffect: { workspaceState: 'decluttered' },
    },
    {
        tag: StressActionTag.SUNLIGHT_FRESH_AIR,
        need: NeedTag.STRESS,
        costEnergy: -0.04,
        costTime: 0.5,
        rewardSatisfaction: 0.6,
        rewardSecondary: { HEALTH: 0.2, RESILIENCE: 0.2, MOOD: 0.2 as any },
        requiresLocation: 'yard|green|balcony',
        socialImpact: { CALM: 0.2 as any },
    },
    {
        tag: StressActionTag.HOT_BATH_SOAK,
        need: NeedTag.STRESS,
        costEnergy: -0.06,
        costTime: 0.8,
        rewardSatisfaction: 0.75,
        rewardSecondary: { HEALTH: 0.3, RESILIENCE: 0.3, MORALE: 0.2 },
        requiresLocation: 'baths|tub_room',
        tradeEffect: {
            firewood: -1,
            herbs: -1 | (0 as any),
            oil: -1 | (0 as any),
        },
        ownershipEffect: { bathSlot: 'booked' },
    },
    {
        tag: StressActionTag.AROMA_OR_INCENSE,
        need: NeedTag.STRESS,
        costEnergy: -0.04,
        costTime: 0.4,
        rewardSatisfaction: 0.55,
        rewardSecondary: { HEALTH: 0.1, JOY: 0.2 as any, CLARITY: 0.1 },
        tradeEffect: { incense: -1 | (0 as any), resin: -1 | (0 as any) },
        socialImpact: { CALM: 0.2 as any },
    },
    {
        tag: StressActionTag.EVENING_UNWIND_RITUAL,
        need: NeedTag.STRESS,
        costEnergy: -0.06,
        costTime: 0.7,
        rewardSatisfaction: 0.7,
        rewardSecondary: { STABILITY: 0.3, PRIVACY: 0.2, RESILIENCE: 0.3 },
        requiresLocation: 'hearth|bunks',
        socialImpact: { ROUTINE: 0.3 as any, PANIC: -0.1 as any },
        ownershipEffect: { curfewReady: 'true' },
    },
];
