export type {
  Biome,
  CharacterSkill,
  CharacterTechnique,
  ConfigConsumerNeedProfile,
  ConsumerAgeBand,
  ConsumerNeedProfile,
  DomainAdminConfig,
  Good,
  GoodLevel,
  GoodProfile,
  LegacyGood,
  ProductionChain,
  ProductionGoodQuantity,
  ProductionRecipe,
  RationItem,
  RationLineResult,
  RationResult,
  RationTemplate,
  SkillDefault,
} from '@wohex/domain-data/economy';
